### ISSUE TITLE
Can‘t get the clear audio when eval at step 871k on LJSpeech-1.0

### ISSUE THREAD

**Issue by JK1532** [keithito/tacotron#100]
Hi  @keithito,thanks fot a great implementation.
    I have trained 871k steps on LJSpeech-1.0 data, but I can't get any clear audio.I didn't change any hparams int the hparams.py.Here is my audio sample at step 871k.
text:Talib Kweli confirmed to AllHipHop that he will be releasing an album in the next year.

[eval-871000.zip](https://github.com/keithito/tacotron/files/1605283/eval-871000.zip)
![step-871000-align](https://user-images.githubusercontent.com/23287555/34592172-3aadd69a-f1fd-11e7-8a67-b4f998642b7a.png)
  please help.
  Sorry my English.

**Comment by keithito** [comment]
Hmm... that's unexpected. And the alignment doesn't look great either. Maybe it's possible the model can get stuck in a local minimum where it doesn't generate intelligible speech. If that's the case, I think the only option might be to start over. Sorry!

If you attach your train.log file, I can take a look and make sure that something else isn't going wrong.

**Comment by JK1532** [comment]
Thanks for your reply.
   In my training process,the model has been interrupted several times,and I use the restore_step to re-train the model. I don't know if this would lead to the bad result.And now I begin to start over.
   A part of the train.log has been lost.Here is the exixting log.
[log.zip](https://github.com/keithito/tacotron/files/1605762/log.zip)

**Comment by wotulong** [comment]
Nancy dataset is a good candidate.

**Comment by JK1532** [comment]
OK ,thanks @wotulong

**Comment by keithito** [comment]
Your loss looks higher than it should be at this point. If you point tensorboard at your log directory, you can see a graph of the loss over time. If you see a sudden spike anywhere, try restarting at a checkpoint just prior to the spike.
