### ISSUE TITLE
Training with GPU 1080 and serving with Tesla K80

### ISSUE THREAD

**Issue by tuong-olli** [keithito/tacotron#101]
I train the model with GPU 1080 Ti and evaluate in google cloud server with Tesla K80. But it can not restore model and error:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [276,256] rhs shape= [277,256]
I find a loss in model/tacotron.py
embedding_table = tf.get_variable(
        'embedding', [len(symbols), 256], dtype=tf.float32,
        initializer=tf.truncated_normal_initializer(stddev=0.5))
Embedding size [len(symbols), 256] have error

**Comment by youssefsharief** [comment]
How did you resolve that?

**Comment by tuong-olli** [comment]
@youssefsharief I failed in defining "_characters" in symbols.py. I trained model with a list of characters and evaluated model with another characters. I fixed it and the model can completely run in Tesla K80.

**Comment by youssefsharief** [comment]
@tuong-olli  great thank you
