### ISSUE TITLE
Wave generated from eval.py seems to have no pitch/tone 

### ISSUE THREAD

**Issue by bearlu007** [keithito/tacotron#103]
First of all , thanks very much to the author for this great implementation. 
Currently , I am using this code for Mandarin modeling and synthesis.
The validation waveform generated from training process seems quite good , and also the alignment file.
By the way, I am using a male voice Mandarin database , and around 80 hours.
The other parameters are the same with default . 
I have tried to use both 1. UTF-8 Chinese Characters . 2. Pinyin sequence without tone and 3. Pinyin sequence with explicit tone marks. 

I think all of them generate good result in training , but the eval.py result seems to have no tone or pitch for all of them. Attachments are waves and alignments. Any suggestions ?
Thank you . 

![step-58000-align](https://user-images.githubusercontent.com/8582547/34923159-1ad20596-f94e-11e7-812b-589021d2a3cb.png)

[waves.zip](https://github.com/keithito/tacotron/files/1630035/waves.zip)

Pinyin sequence with explicit tone marks. this seems better with eval.py  . However， the result is still not as good as validation. 
Any suggestions to improve the prosody of evaluation waveform ?

**Comment by bearlu007** [comment]
Now the training steps are 82000, Still you can see the testing waveform have no pitch. Attachments are the files generated at the 82000 training steps.

![step-82000-align](https://user-images.githubusercontent.com/8582547/34956180-e348026c-f9dc-11e7-82ad-f90eb23da88a.png)
[82000wave.zip](https://github.com/keithito/tacotron/files/1632624/82000wave.zip)

**Comment by keithito** [comment]
It's strange that the eval audio sounds so different from the training audio. Is your training data a single speaker?

**Comment by bearlu007** [comment]
Thanks Keith . I think it is because of the database. I changed to another female database  and it works fine. Please see attached samples .  I think it is the pitch of the male speaker is so low that we need to tune the parameters for the Tacotron to make it work .   Any suggestions for what to tune ? Thank you very much !

![step-41000-align](https://user-images.githubusercontent.com/8582547/35004908-88cbad14-faa6-11e7-8b00-9ac81fa52d98.png)

[samples.zip](https://github.com/keithito/tacotron/files/1636294/samples.zip)

**Comment by keithito** [comment]
Interesting! It might make sense to allocate more bandwidth in the mel spectrogram to lower frequencies. There's no hyperparameter to do this, but you could do this by passing the fmin and fmax parameters when generating the mel basis:
https://github.com/keithito/tacotron/blob/d88640b7c0003923df3ee3b79155205997ec0bd7/util/audio.py#L133

**Comment by yyt233** [comment]
The quality of the data you generate is so great!Can I ask you a few questions?
How many hours of your female dataset?
Is there any data processing before training your model?
Thank you!
