### ISSUE TITLE
[question] Is it possible to use data like this?

### ISSUE THREAD

**Issue by rraallvv** [keithito/tacotron#104]
I was thinking that maybe I could download a bunch of videos like [this one](https://www.youtube.com/watch?v=oQYXmOcLy2o), with all their transcriptions and use it to feed tacotron. Those videos are targeted to pre-K audiences, so the voice actors use some particular inflections in some cases, and silly voices. Since those voice actors are doing that stuff for a living, they might use the same patters over and over in a sort of automated way, so when they see capitalized words or quote marks they might be using the same inflections or expressiveness.

Do you think tacotron could come up with something that resembles those actors' performances?

How big should be the data for the training?

As a side note, they just [published a paper](https://google.github.io/tacotron/publications/tacotron2/index.html) for the new version of tacotron, are there any plans for using tensorflow for that implementation too?

Keep up the good work.

**Comment by Ryel** [comment]
I don't think the output would be great due to the variation in cadence but you wont know until you try it.

As far as Tacotron 2 implentation, look here #90

**Comment by rraallvv** [comment]
@Ryel I'm in the process of installing tensor flow now, there are some many things I want to try. If I can pull it off I'll post it here. Thanks.
