### ISSUE TITLE
what's the maximum support text length of generating voice of tacotron?

### ISSUE THREAD

**Issue by luweishuang** [keithito/tacotron#107]
I trained a model in mandarin of male voice, the training waveset is  within  15 seconds and the male speaker‘s speed of speech is faster, as this  
[training_samples.zip](https://github.com/keithito/tacotron/files/1650462/training_samples.zip)
I do 200k iter with default hparams except sample_rate=16000, max_iters=300 and I get some generated wavs as 
[eval_samples.zip](https://github.com/keithito/tacotron/files/1650681/eval_samples.zip)

1.  the long length text often has a wrong generated wav like 74-eval-21000-*.wav in eval_samples.zip and I found the first half often can pronunciate correctly and the left often pronunciate wrong. Probably a dozen Chinese characters can pronunciate correctly.
2.  a short length text generated wavs sometime will miss some words or just can't truncated at the end of the sentence, like 9-eval-200000-请问你是李涛本人吗.wav in eval_samples.zip or 74-eval-21000-首先我们先从一个极端例子出发来思考，有一家公司总共发行一亿股*.wav 
3. I generated text’s grondtruth by xunfei asr engine and it's has nearly 25 percent error rate. May it has some effect in model training
4. My trainingSet's speaker speak aloudy, but I found the volume of generated wavs almost  is relatively small and it have some relationship with generated wav's quality

**Comment by seymour1** [comment]
+1 on this. It seems that there's a lot of assumptions in the lengths of the .wavs and the .txts: are they all on the order of sentences? It's especially hard to tell what the Blizzard parser is doing (does the dataset come with times corresponding to sentences?)
