### ISSUE TITLE
Tensorflow with TCMalloc

### ISSUE THREAD

**Issue by pineking** [keithito/tacotron#11]
>TCMalloc seems to improve training speed and avoids occasional slowdowns seen with the default allocator. You can enable it by installing it and setting LD_PRELOAD=/usr/lib/libtcmalloc.so.

@keithito are there some docs or experiments/benchmark to show this conclusion? does this depend on the version of tensorflow?

**Comment by keithito** [comment]
Sorry, I don't have any real benchmarks. But anecdotally, without tcmalloc, I was getting ~1.2 sec/step, and then maybe 25% of the time, things would slow down a lot to ~2 sec/step. htop showed a lot of time spent in kernel threads. After switching to tcmalloc, I consistently get ~1.1 sec/step all the time. I've only tried this with Tensorflow 1.2.

There's some discussion of a similar issue here:
https://github.com/tensorflow/tensorflow/issues/3009#issuecomment-235993119

**Comment by pineking** [comment]
thanks for your comment, I will have a try.
