### ISSUE TITLE
The shape of mel targets and mel outputs differs in model. Maybe too many frames in the wave?

### ISSUE THREAD

**Issue by begeekmyfriend** [keithito/tacotron#110]
When I train `thchs30` mandarin data set, I preprocessed pinyin phones as text in `train.txt`,  I got an exception as follows:
```shell
2018-01-26 18:28:38.296663: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1210,80] vs. [32,1000,80]
	 [[Node: model/loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](datafeeder/input_queue_Dequeue/_25, model/inference/Reshape)]]
```
It seems the second dimension in the shape of `mel_targets` and `mel_outputs` in model [tacotron.py](https://github.com/keithito/tacotron/blob/master/models/tacotron.py#L113) differs so that `tf.reduce_mean` method threw an error to stop the run.

And I picked up one of the wave files whose number of frames exceeds 1000 and train it alone and then It reappeared. So I guess the number of frames more than 1000 would make this issue, since the shape of `mel_outputs` is set as [32,1000,80].

Can you tell me in which hyper parameter can I modify to avoid this exception?

**Comment by keithito** [comment]
Please see the last bullet point here:
https://github.com/keithito/tacotron#notes-and-common-issues

**Comment by begeekmyfriend** [comment]
Oh yes. My negligence.
