### ISSUE TITLE
Output two channel

### ISSUE THREAD

**Issue by tuong-olli** [keithito/tacotron#113]
How do i train the model that synthesis 2 channel audio?

**Comment by keithito** [comment]
I think you could concatenate both channels into a single vector going through the model. You'd need to modify a few places in the code:

- In [audio.py](https://github.com/keithito/tacotron/blob/master/util/audio.py) modify load_wav and sav_wav to handle 2 channels. librosa supports this.
- In your preprocessor, compute spectrograms and mel spectrograms for each channel, and then concatenate them before saving (alternately, you could save spectrograms for each channel and concatenate them later during training).
- During synthesis, split the output of the model into 2 channels before calling inv_spectrogram_tensorflow.
