### ISSUE TITLE
Can't quite solve this preprocess.py issue

### ISSUE THREAD

**Issue by SoulFireMage** [keithito/tacotron#114]
Hi 

I've followed the instructions but haven't found a way past this issue?
Why is it trying to do stuff in c:\\users?
 
C:\TM2V2>python preprocess.py --dataset ljspeech
Traceback (most recent call last):
  File "preprocess.py", line 50, in <module>
    main()
  File "preprocess.py", line 46, in main
    preprocess_ljspeech(args)
  File "preprocess.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "C:\TM2V2\datasets\ljspeech.py", line 26, in build_from_path
    with open(os.path.join(in_dir, 'metadata.csv'), encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Richard/tacotron\\LJSpeech-1.0\\metadata.csv'

**Comment by SoulFireMage** [comment]
I did solve it, I think. It's doing something long winded now.

Move the speech files to the Users folder the error message moans about. There is very likely a better answer - I'm quite the n00b on any of this python stuff. However this is getting my preprocessing step done. Probably means I'll have other issues next :).

**Comment by keithito** [comment]
There's a --base_dir flag that lets you tell it what directory to work in. By default it's a "tacotron" directory under your home directory.

**Comment by doctor-xiang** [comment]
hello @SoulFireMage ，i met the same erro ,do you solve the problem?
