### ISSUE TITLE
Automatic segmentation based on silences in the recording

### ISSUE THREAD

**Issue by yyt233** [keithito/tacotron#115]
Hello,everyone!
As described in the LJ Speech dataset:The audio clips range in length from approximately 1 second to 10 seconds. They were segmented automatically based on silences in the recording. Clip boundaries generally align with sentence or clause boundaries, but not always. 
Does anyone can tell me about the implementation of automatic segmentation?
I would be very appreciate！

**Comment by keithito** [comment]
[This gist](https://gist.github.com/keithito/771cfc1a1ab69d1957914e377e65b6bd) has the segmentation code. There's a little bit of boilerplate related to LJ speech in there, but the rest should be reusable.

**Comment by yyt233** [comment]
Thank you very much!But I can not open this link.

**Comment by yyt233** [comment]
Thank you very much!I'll try it.
