### ISSUE TITLE
GPU Usage?

### ISSUE THREAD

**Issue by SoulFireMage** [keithito/tacotron#116]
It looks like it doesn't use GPU by default - is there a way to set this up please? I am looking on the tensorflow site but can't see how to tell train.py to do this.

**Comment by morelen17** [comment]
Do you use tensorflow-gpu? And have you been able to train other models using tensorflow on your gpu?

**Comment by SoulFireMage** [comment]
I am using tensorflow-gpu and I've cuda 9.1 installed. Didn't get any warning messages either. This is the first thing I've tried to do with it.

**Comment by keithito** [comment]
Can you check that the GPU is enabled following the instructions [here](https://stackoverflow.com/a/38019608) and include the output?

**Comment by SoulFireMage** [comment]
It's going to be q job for tomorrow evening now. Thanks Keith though.

**Comment by entn-at** [comment]
@SoulFireMage did you compile Tensorflow from source? I'm asking because the binary 1.5 release package does not support CUDA 9.1 (see https://github.com/tensorflow/tensorflow/issues/15656).

**Comment by SoulFireMage** [comment]
I didn't, I don't have experience with c++ compilation so that hadn't occurred to me.

What got me started yesterday was I needed a really good text to speech system and went hunting for open source tacotron. 

I got a preteained model working but it needed to be trained for longer hence my trying to do this. So I'm rather a beginner with the libraries involved.

**Comment by entn-at** [comment]
I'd suggest following @keithito's suggestion to check that the GPU is enabled and, if need be, try downgrading to CUDA 9.0

**Comment by edwinlimlx** [comment]
Hi, managed to setup training on GPU, however it's only running at between 30-50% with nvidia-smi. Is there a way to increase the training performance?

**Comment by Jackiexiao** [comment]
check your cuda version
```
cat /usr/local/cuda/version.txt
```
if your CUDA Version 8.0, downgrade to CUDA 9.0 or use tensorflow1.4.0 like
```
pip install tensorflow-gpu==1.4.0
```
check again in python shell
```
>>> import tensorflow as tf 
>>> tf.__version__
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```
