### ISSUE TITLE
Severe memory leak?

### ISSUE THREAD

**Issue by sonach** [keithito/tacotron#12]
HI, all: 
I observed memory leak. Six days before, the memory was about 24% of 256GB RAM; Now it is about 85% of 256GB RAM. Now it is about 300Ksteps.
Any one encounter this? 
(I set use_dict to True, and other hyperparams keeps the same)
Thank you!

**Comment by keithito** [comment]
Hi, I've been able to run for over a week using less than 32 GB of RAM (I don't know what the peak usage was, but the machine has only 32 GB of RAM, so it must have been less than that). Some questions may help narrow down the issue:
1. Are you training on CPU or GPU?
2. Are you using TCMalloc? It could be that fragmentation gets really bad with the default allocator (see README).

If the memory usage gets problematic, you can safely stop training and then restart from a recent checkpoint with the `--restore_step` flag. Checkpoints are saved every 1000 steps by default.

**Comment by sonach** [comment]
@keithito Thank you for the quick reply!
So you enable TCMalloc for your train running on 32GB RAM? I will try to enableTCMalloc.
And yes, the restore_step is really a alternative solution  too!

I am training on GPU with 16GB video memory, and the Main memory is 256 GB, the speed is  about 1.85 second/step.

**Comment by zuoxiang95** [comment]
I have installed the TCMalloc, and run 
LD_PRELOAD="/usr/local/lib/libtcmalloc.so" python2 train.py
but the speed is still 1.8 second/step

**Comment by keithito** [comment]
Closing out issues that haven't had any activity in a while. Please feel free to reopen if this is still a problem. Thanks!

**Comment by begeekmyfriend** [comment]
@zuoxiang95 If you decrease the value of the hyper parameter of `max_iters`, you will get less time per step ;-)

**Comment by begeekmyfriend** [comment]
@zuoxiang95 If you decrease the value of the hyper parameter of `max_iters`, you will get less time per step ;-)
