### ISSUE TITLE
Time limit for audio generation

### ISSUE THREAD

**Issue by chenhong1115** [keithito/tacotron#124]
HI：
Excuse me，The generated audio is only six seconds，Can audio time be extended?

**Comment by pineking** [comment]
see https://github.com/keithito/tacotron/blob/master/README.md#notes-and-common-issues

>During eval and training, audio length is limited to max_iters * outputs_per_step * frame_shift_ms milliseconds. With the defaults (max_iters=200, outputs_per_step=5, frame_shift_ms=12.5), this is 12.5 seconds.
If your training examples are longer, you will see an error like this: Incompatible shapes: [32,1340,80] vs. [32,1000,80]
To fix this, you can set a larger value of max_iters by passing --hparams="max_iters=300" to train.py (replace "300" with a value based on how long your audio is and the formula above).

**Comment by chenhong1115** [comment]
ok，thank you
