### ISSUE TITLE
Embeddings code

### ISSUE THREAD

**Issue by zuoxiang95** [keithito/tacotron#13]
hi guys, i can‘t understand the embeddings code in tracotron.py . It looks like to random a array (shape is num_symbol*256)  in normal distribution, and select the symbol's ID lines?

**Comment by keithito** [comment]
It's using tf.nn.embedding_lookup to map each symbol (character) in the input to a 256D embedding vector. The embedding_lookup operation treats each symbol as an index and pulls out the corresponding row in the embedding table.

The embeddings are not fixed, but instead are initialized randomly and updated during training. Over time, they should learn to capture some sort of structure that is helpful to the model in performing its task.

**Comment by zuoxiang95** [comment]
@keithito Thanks for your answer. But in the code , i did not see the process of  updating the embedding table.

**Comment by keithito** [comment]
They get updated through backpropagation, just like everything else.
