### ISSUE TITLE
train.py path error

### ISSUE THREAD

**Issue by ranawsamy** [keithito/tacotron#130]
I get this error while trying to train after the preprocessing step
![capture](https://user-images.githubusercontent.com/25366533/37545594-01c3810c-2972-11e8-87bc-08dbad14f076.PNG)

**Comment by keithito** [comment]
Did you run preprocess.py first? If so, maybe it's a problem with the paths on Windows, though others have been able to train on Windows without a problem.

**Comment by ranawsamy** [comment]
while preprocessing i found this error,but the training folder was  created containing a lot of files 
![capture](https://user-images.githubusercontent.com/25366533/37547344-c68293a0-2979-11e8-8ed1-cd4d2db8568d.PNG)

**Comment by keithito** [comment]
Oh, can you try again with the latest version of the code. There was recently a PR that fixed the path (it was pointing at the directory for LJSpeech-1.0, but 1.1 is the latest:
https://github.com/keithito/tacotron/pull/131
