### ISSUE TITLE
Installed as described, but "No module named 'falcon'"

### ISSUE THREAD

**Issue by SandUhrGucker** [keithito/tacotron#134]
The install looks ok:
`Successfully installed Unidecode-0.4.20 audioread-2.1.5 cycler-0.10.0 decorator-4.2.1 falcon-1.2.0 inflect-0.2.5 joblib-0.11 librosa-0.5.1 llvmlite-0.22.0 matplotlib-2.0.2 numba-0.37.0 numpy-1.13.0 pyparsing-2.2.0 python-dateutil-2.7.1 python-mimeparse-1.6.0 pytz-2018.3 resampy-0.2.0 scikit-learn-0.19.1 scipy-0.19.0 tqdm-4.11.2`

But if I want to start the demo:
```
munsch@Metis ~/Downloads/tacotron $ python3 demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt
Traceback (most recent call last):
  File "demo_server.py", line 2, in <module>
    import falcon
ModuleNotFoundError: No module named 'falcon'
```

**Comment by fuzeller** [comment]
The error refers to "module not found" ('falcon'), which is not in pip's list, so you need to install it:  (pip install falcon).
See pip --help, too.

Or, Google "ModuleNotFoundError: No module named 'falcon'" - you're certainly not the first to run into this.

**Comment by SandUhrGucker** [comment]
THAT exactly confuses me. Because falcon was in the requirements, pip installed it already successfully.
`pip list |grep falcon`
shows:
`falcon (1.2.0)`
I'm very famila with Linux but not experienced with Python. Any hint what else could be wrong, or what I should try?

**Comment by toannhu** [comment]
@SandUhrGucker  I think you shoud use `pip3 install falcon` instead of `pip` because `pip` will install package for python 2

**Comment by SandUhrGucker** [comment]
Good Idea, but pip3 also shows falcon 1.2.0 installed:
```
munsch@Metis ~/Downloads/tacotron $ pip3 list |grep falcon
falcon (1.2.0)
```

**Comment by toannhu** [comment]
@SandUhrGucker just use `pip3 install -r requirements.txt` follow the README.md and try to run `demo.py` again. That's weird if this thing doesn't solve the problem.

**Comment by JKalash** [comment]
For anyone facing the issue when installing, this worked for me:
`python3 -m pip install -r requirements.txt`

**Comment by fiizii** [comment]
having this issue aswell, windows 10 64bit
