### ISSUE TITLE
What does the size of pixels in alignment images present?

### ISSUE THREAD

**Issue by begeekmyfriend** [keithito/tacotron#135]
![step-25000-align](https://user-images.githubusercontent.com/6031938/38007334-88200056-327b-11e8-8d37-3564b06eeb97.png)
![35375844-5ab7f9a6-015d-11e8-9cda-591568d98c5e](https://user-images.githubusercontent.com/6031938/38007360-aafb7510-327b-11e8-9da6-b655d12075d9.png)
The thin one is the alignment for `THCHS30` Chinese mandarin dataset, and the thick one is trained by Keith Ito with his `LJ Speech`. Do anyone know what is the different and made the size of pixels of alignment image?

**Comment by NTT123** [comment]
@begeekmyfriend, It's perhaps because of the scale of the X and Y axes (60 v.s. 200).

**Comment by begeekmyfriend** [comment]
Then why does the scale of the axes (aka decoder timestep) of my alignment present larger than that of Ito's? Which one is the better? I have not looked into the code closly.

**Comment by youssefsharief** [comment]
@begeekmyfriend This is normal if the thick pixles represent a relatively short audio file. The pixel thickness correlates inversely with the duration of the audio file. 
Let me try to help you once. You helped a lot in the past. :)
