### ISSUE TITLE
unexpected keyword argument 'state'

### ISSUE THREAD

**Issue by dagbdagb** [keithito/tacotron#138]
Getting this when playing with your tacotron2-wip branch. 
My tensorflow install is 1.7.0-rc, but got the same with 1.6 as released. 

Any idea?

dagb@hp8570w ~/tacotron $ python3 eval.py --checkpoint ./tmp2/model.ckpt-800000/model.ckpt-800000                                                                                                           
WARNING:tensorflow:From /home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tenso                                                        rflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.                                                                                                       
Instructions for updating:                                                                                                                                                                                   
Use the retry module or similar alternatives.                                                                                                                                                                
Hyperparameters:                                                                                                                                                                                             
  adam_beta1: 0.9                                                                                                                                                                                            
  adam_beta2: 0.999                                                                                                                                                                                          
  attention_depth: 128                                                                                                                                                                                       
  batch_size: 32                                                                                                                                                                                             
  cleaners: english_cleaners                                                                                                                                                                                 
  decoder_lstm_units: 1024                                                                                                                                                                                   
  embedding_dim: 512                                                                                                                                                                                         
  encoder_conv_channels: 512                                                                                                                                                                                 
  encoder_conv_layers: 3                                                                                                                                                                                     
  encoder_conv_width: 5                                                                                                                                                                                      
  encoder_lstm_units: 256                                                                                                                                                                                    
  expand_conv_channels: 512                                                                                                                                                                                  
  expand_conv_layers: 5                                                                                                                                                                                      
  expand_conv_width: 5                                                                                                                                                                                       
  expand_lstm_units: 256                                                                                                                                                                                     
  frame_length_ms: 50                                                                                                                                                                                        
  frame_shift_ms: 12.5                                                                                                                                                                                       
  griffin_lim_iters: 60                                                                                                                                                                                      
  initial_learning_rate: 0.001                                                                                                                                                                               
  learning_rate_decay_halflife: 100000                                                                                                                                                                       
  max_iters: 200                                                                                                                                                                                             
  max_mel_freq: 7600                                                                                                                                                                                         
  min_level_db: -100                                                                                                                                                                                         
  min_mel_freq: 125                                                                                                                                                                                          
  num_freq: 1025                                                                                                                                                                                             
  num_mels: 80                                                                                                                                                                                               
  outputs_per_step: 5                                                                                                                                                                                        
  postnet_conv_channels: 512
  postnet_conv_layers: 5
  postnet_conv_width: 5
  power: 1.5
  ref_level_db: 20
  sample_rate: 20000
  use_cmudict: False
Constructing model: tacotron
Traceback (most recent call last):
  File "eval.py", line 53, in <module>
    main()
  File "eval.py", line 49, in main
    run_eval(args)
  File "eval.py", line 32, in run_eval
    synth.load(args.checkpoint)
  File "/home/dagb/tacotron/synthesizer.py", line 18, in load
    self.model.initialize(inputs, input_lengths)
  File "/home/dagb/tacotron/models/tacotron.py", line 85, in initialize
    maximum_iterations=hp.max_iters)                                        # [N, T_out/r, M*r]
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 304, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3208, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2946, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2883, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 249, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 137, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 378, in call
    output, res_state = self._cell(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1283, in call
    cur_inp, new_state = cell(cur_inp, cur_state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/dagb/tacotron/models/rnn_wrappers.py", line 51, in call
    output, res_state = self._cell(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 232, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/python/layers/base.py", line 714, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1411, in call
    self._attention_layers[i] if self._attention_layers else None)
  File "/home/dagb/.local/lib64/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1048, in _compute_attention
    cell_output, state=attention_state)
TypeError: __call__() got an unexpected keyword argument 'state'

**Comment by NTT123** [comment]
You should replace file `https://github.com/keithito/tacotron/blob/tacotron2-work-in-progress/models/attention.py` by file `https://github.com/MycroftAI/mimic2/blob/master/models/attention.py`
it is because there is a difference in the recurrent interface of the new Tensorflow version.

**Comment by dagbdagb** [comment]
@NTT123 Thank you. That did the trick.

**Comment by dagbdagb** [comment]
For the benefit of others:
wget https://raw.githubusercontent.com/MycroftAI/mimic2/master/models/attention.py

**Comment by keithito** [comment]
I've updated the branch so it'll work with the latest version of tensorflow.
