### ISSUE TITLE
Why the sound is full of noise?

### ISSUE THREAD

**Issue by 15857541616** [keithito/tacotron#143]
I have use the pre-trained models, and trained the model using LJspeech dataset ,but all the results are full of noisy , I try to improve the value of hparams.py power=4(default is 1.5) , the noise is little than before, but the sound is still blurry ,not clear as the Audio Samples, Can anyone tell me why? @keithito

**Comment by 15857541616** [comment]
I have solve the problem...

**Comment by butterl** [comment]
@15857541616  can you share the way how you solve the problem?

**Comment by 15857541616** [comment]
https://github.com/keithito/tacotron/issues/139
