### ISSUE TITLE
Is this repository original google tacotron github??

### ISSUE THREAD

**Issue by weegwangjin** [keithito/tacotron#145]
I have a question.

google presented tacotron paper

but i couldn't find google tacotron source.

@keithito  just implemented voice synthesis program base on tacotron paper???
or this repo is original google tacotron source???

**Comment by NTT123** [comment]
@weegwangjin No, this is **not** a google project.

**Comment by weegwangjin** [comment]
@NTT123 so, google didn't open their source??

**Comment by NTT123** [comment]
Yes, they didn't.
