### ISSUE TITLE
Cannot train with outputs_per_step != 5

### ISSUE THREAD

**Issue by duvtedudug** [keithito/tacotron#146]
I'm trying to change outputs_per_step to 1 and train

But I quickly get...

Initialized Tacotron model. Dimensions: 
  embedding:               256
  prenet out:              128
  encoder out:             256
  attention out:           256
  concat attn & out:       512
  decoder cell out:        256
  decoder out (2 frames):  160
  decoder out (1 frame):   80
  postnet out:             256
  linear out:              1025
Starting new training run at commit: None
Generated 32 batches of size 32 in 1.182 sec
**Exiting due to exception: Incompatible shapes: [32,544,80] vs. [32,400,80]**
         [[Node: model/loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](datafeeder/input_queue_Dequeue/_17, model/inference/Reshape)]]
         [[Node: model/optimizer/gradients/model/inference/post_cbhg/highway_3/mul_1_grad/Shape/_269 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2714_...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'model/loss/sub', defined at:
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    train(log_dir, args)

... etc.

Any ideas greatly appreciated!

**Comment by duvtedudug** [comment]
Further investigation shows that

outputs_per_step = 1
Exiting due to exception: Incompatible shapes: [32,744,80] vs. [32,**200**,80]
outputs_per_step = 2
Exiting due to exception: Incompatible shapes: [32,744,80] vs. [32,**400**,80]
outputs_per_step = 3
Exiting due to exception: Incompatible shapes: [32,744,80] vs. [32,**600**,80]
outputs_per_step = 4+
works...

Anybody know where does it limit to 200 outputs per outputs_per_step???

**Comment by youssefsharief** [comment]
@duvtedudug Are you using long samples or a non ascii language?
