### ISSUE TITLE
Good results at training checkpoints, but silence when running demo server.

### ISSUE THREAD

**Issue by TheNarrator** [keithito/tacotron#147]
Hey there,

The language I'm working with is **Mongolian**.  I wanted to see if I can get the model to overfit on a small dataset, and ran it with audio of about an hour. The samples created inside the log folder at checkpoints started to sound more or less like the original audios at 14k steps. 

The problem is when those checkpoint files are used to run the demo server, the synthesized audios are silent. Here are the things I modified thus far:

- Due to small differences between the Mongolian and Russian alphabets, the `transliteration_cleaners` doesn't quite get the words right. So I've run 2 different trainings. 1 with the default characters list using `transliteration_cleaners`, and other with Cyrillic characters using `basic_cleaners`. The synthesized audios at checkpoints are excellent for both.

- The audio files I had turned out to be a bit longer, so I used `--hparams="max_iters=500"` at training time.

- Changed `batch_size` to 16 to fit into memory.

I noticed that my dataset had **2.0 sec** of silence at the beginning of all audios, so I tried the fix suggested in #92 but this didn't make much difference (produced jibberish even when using sentences from the training set).

**Comment by rafaelvalle** [comment]
Did your model learn to attend ?

**Comment by TheNarrator** [comment]
After you mentioned `attention`, I went back and looked at #141 and #144. Thank you.
Here's what the alignment looks like on my end:
![step-44000-align](https://user-images.githubusercontent.com/1825013/38765046-e19aa752-3fec-11e8-8467-c0e8df13ac23.png)

So now I see clearly that the alignment is very bad here. Since my decoder timestep is at 175, the alignment shouldn't be a diagonal as mentioned in other issues, but still this is pretty bad. In #122 @keithito mentioned that trimming the unnecessary silences helps with alignment. I'll go ahead and try that first!

Are there any other issues I should be looking into?

**Comment by TheNarrator** [comment]
A little late. Trimming the silences **did** solve the issue.
