### ISSUE TITLE
error message in the middle of training

### ISSUE THREAD

**Issue by joongbo** [keithito/tacotron#150]
I'm trying to train Tacotron model with my data after preparing as LJSpeech.
However, I got an error message below in the middle of training.

----------------------------------------------------------------------------------------------------
...
Step 254     [0.789 sec/step, loss=0.15052, avg_loss=0.18137]
Step 255     [0.791 sec/step, loss=0.16074, avg_loss=0.18112]
2018-04-19 10:50:26.599681: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [32,1095,80] vs. [32,1000,80]
         [[Node: model/loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](datafeeder/input_queue_Dequeue/_31, model/inference/Reshape)]]
...
----------------------------------------------------------------------------------------------------

I think it is about unmatched shapes of "mel_targets" and "mel_outputs" of the model.
Second elements of shapes (i.e., 1095, 1000) is the largest sequence length of the mel-spectrogram in the current batch, right?
I found a fact that this error occurs only when this length is larger then 1000.
But I also found that there is no error on LJSpeech dataset.

Here are statistics (max/min/mean/std) of paly times of wave files in LJSpeech and my data
LJSpeech (sec): 10.096 / 1.110 / 6.573 / 2.185
my data   (sec): 34.139 / 0.585 / 4.460 / 3.065

Can anybody help me?

**Comment by keithito** [comment]
Please see the fifth item here:
https://github.com/keithito/tacotron#notes-and-common-issues

**Comment by joongbo** [comment]
@keithito Oh, Thank!
