### ISSUE TITLE
How to optimize?

### ISSUE THREAD

**Issue by hq23** [keithito/tacotron#151]
Sorry if my question might still sound a little noobish, I just started to read into deeplearning for speech synthesis. 

I've read in another "issue" that keithito achieved around 1 second per step with a GTX1080 Ti. I am currently running the training around 4 seconds per step on the same card.

Besides reducing the batchsize to prevent OOM errors I did not change anything. 

Could anyone please give me some advice on which parameters I can change to try and speed it up?

Thank you very much.

**Comment by shaunmayberry** [comment]
There is a dependency on the length of your sentences, if your current batch has a long sentence that step will take slightly longer to process than a batch with short sentences. Also make sure the max_iter in hparams is not set to a value that is much longer than the longest sentence in your data, taking into account the outputs_per_step. So for example if the longest sentence in your corpus has 1000 frames, and your outputs_per_step is set to 5, then you could set max_iter to a value slightly over 200 ( 1000 frames / 5 reduction factor).
