### ISSUE TITLE
M-AILABS Speech Dataset

### ISSUE THREAD

**Issue by AudhootChavan** [keithito/tacotron#159]
@keithito  Hi, I'm trying to train the model on US-en(male speaker) data from M-AILABS dataset. I have trained for 100k steps so far but the alignment is still bad.  

![step-102000-align](https://user-images.githubusercontent.com/12958946/39420482-5ac69fb8-4c82-11e8-86d8-a5de17bf1ad0.png)

Maybe I'm doing something wrong with the preprocessing part. Can you help me out? 

This is the gist of the changes I've made for preprocessing : 
https://gist.github.com/AudhootChavan/0689a7a0b54476cc16aaf1f33ecffddb

The folder structure of 'en_US' containing the data -->

```

tacotron
  |- en_US
      |- hunters_space
             |- metadata.csv
             |- wavs
      |- pink_fairy_book
             |- metadata.csv
             |- wavs
      |- pirates_of_ersatz
             |- metadata.csv
             |- wavs
      |- poisoned_pen
             |- metadata.csv
             |- wavs
      |- silent_bullet
             |- metadata.csv
             |- wavs

```

**Comment by keithito** [comment]
Are you trimming silence from the start and end of your wavs? Attention tends to be very sensitive to this. You can use librosa to trim:
https://librosa.github.io/librosa/generated/librosa.effects.trim.html

Also, how much training data do you have?

**Comment by AudhootChavan** [comment]
@keithito  I'm using the English(US) data set (male voice). The length is approximately around 50 hrs.
Here is the link to the entire dataset : 
http://www.m-ailabs.bayern/en/the-mailabs-speech-dataset/

**Comment by rafaelvalle** [comment]
@AudhootChavan some samples from m-ailabs have 500ms silence at the beginning and end of each audio file. Trim them with sox and your model should learn better attention...

**Comment by naumovd** [comment]
@rafaelvalle actually not some samples. All samples have 0.5s silence at start and at the end. It was done on purpose and described in documentation.

**Comment by LearnedVector** [comment]
This dataset looks promising! does anyone have any samples on the output of this dataset from training? Super interested to hear what it sounds like @AudhootChavan @naumovd

**Comment by naumovd** [comment]
@LearnedVector Here is example of training on one of German subset: https://soundcloud.com/dima-naumov/tacotrongermantest 
It is step ~150k, loss is ~0.08. I can't get good results with Ukrainian data - trying to figure out with it.

**Comment by LearnedVector** [comment]
@naumovd that sounds pretty good! Are you trimming the silence at the start and end? if so which method are you using to do that? I've tried trimming using a simple librosa.effects.trim(wav) during the preprocessing step but I still cannot get a good alignment during training for the English us male and female dataset.

**Comment by naumovd** [comment]
@LearnedVector For this training I cut silences. It's improve results a little bit. 
I am using sox for file trimming.
This terminal command can help you
`for f in *.wav
do
    sox $f ../trim/$f trim 0.5 reverse trim 0.5 reverse
done
`
