### ISSUE TITLE
training speed?

### ISSUE THREAD

**Issue by fanskyer** [keithito/tacotron#17]
Thanks for this well written implementation, I am using the LJ dataset and training, and a GTX 1080, it seems i trained 14days at 500K steps, I was wondering what is the machine you are using or special hyper parameters use to get 877K steps in 11days. Thanks!

**Comment by zuoxiang95** [comment]
They say TCMalloc can accelerate the speed of train. You can try it.

**Comment by keithito** [comment]
I'm using a GTX 1080 Ti, which I think is around 30% faster than a GTX 1080.  And also switching to TCMalloc was another 10% gain. Other than that, it's just the default hyperparameters.

**Comment by keithito** [comment]
One other thing: I have all the training data on an SSD. If you're using a spinning disk, that may be the bottleneck.

**Comment by fanskyer** [comment]
thanks! is use_cmudict=True to enforce a phoneme sequence better than the character sequence in the quality wise? how big is the difference? haven't played with it yet. :)
do you have any plan to make it multiple gpu speedup? thanks

**Comment by keithito** [comment]
In my experience, use_cmudict doesn't affect quality. It does allow you to manually override pronunciation at synthesis time for proper nouns or other cases where the model gets it wrong, which I think is an important feature to have in a speech synthesis system.

I don't have any plans to add multi GPU support. If you happen to have multiple GPUs, I think you may be better off training multiple models to try out different hyperparameters. Of course if someone opens a PR that adds multi-GPU support cleanly, I'll gladly take a look :-)

**Comment by GregHewittDA** [comment]
As a point of reference for others - the LJ dataset and my Quadro M4000 yielded 34,000 steps over 18 hours using the settings as-downloaded. I'm 'very' new to this field, so thank you @keithito for the well written implementation. I've just began a run using the VCTK dataset and will be sure to report back comparisons.

**Comment by ElevenGameStudios** [comment]
I am only training on cpu, but i can confirm that using a SSD is a good idea. In my case a lesser cpu + ssd trains faster than a slightly faster processor using a traditional hdd.
