### ISSUE TITLE
How to play the generated audio file?

### ISSUE THREAD

**Issue by erammunawwar** [keithito/tacotron#171]
While training the model, I simultaneously run the eval.py with every 1000th checkpoint.
The audio is synthesised and saved as a .wav file. The size of the file is also not 0, therefore it is not empty.
However, when I try to play the file using VLC or Media Player, it throws an error and is not able to play the audio.
Any suggestions on how to hear the generated audio?

**Comment by erammunawwar** [comment]
I tried Ipython.display.Audio as well.
It gives a 0.00 second audio with this. But the size of the files are almost 500 KiB

**Comment by keithito** [comment]
Can you attach one of the files?

**Comment by erammunawwar** [comment]
[step-82000-audio.zip](https://github.com/keithito/tacotron/files/2000025/step-82000-audio.zip)

**Comment by erammunawwar** [comment]
The audios generated using eval.py also show the same behaviour. Therefore, I have attached only the one generated while training.

**Comment by erammunawwar** [comment]
@keithito Hi! Any suggestion on the issue above? My model is trained upto 120k steps, and none of the generated audio files seem to play anything. When I check the properties of the file, I can see the duration of the audio. And it is not 0seconds in any case.
I can see that the code works pretty well for many people in this forum. Any ideas what I am missing?

**Comment by keithito** [comment]
It seems to be generating a full 9 seconds of silence. Are you sure your training data is getting preprocessed correctly? Perhaps you could plot one of the spectrograms that is output by the preprocessor and make sure it's not empty.

**Comment by fire-python** [comment]
@erammunawwar 
I encounter the same problem.  Have you solved it?
