### ISSUE TITLE
tacotron 2 and tf 1.4 ... got an unexpected keyword argument 'previous_alignments'

### ISSUE THREAD

**Issue by ArashHosseini** [keithito/tacotron#172]
Hey, 
i have failed to evaluate the Tacotron 2 branch with tf 1.4......changed keyword-name, is mentioned [here](https://github.com/Rayhane-mamah/Tacotron-2/issues/12)

**Comment by keithito** [comment]
Sorry, to use that branch, you need at least TF 1.6, for the same reason mentioned in the issue you linked to.
