### ISSUE TITLE
Documentation about speed, loss and convergence

### ISSUE THREAD

**Issue by albertz** [keithito/tacotron#183]
I downloaded the LJ dataset, did the preprocessing and started the `train.py` script (without any arguments, except `--base_dir`, so I guess it uses the defaults). The default options correspond also to the model you can download? Are these the recommended hyper params?
I was wondering what do expect when I do that, esp what speed and what loss. Very early now in training, I see this:

    Step 117     [2.900 sec/step, loss=0.29457, avg_loss=0.56148]

The speed varies a bit (within 2.5-3.0 secs/step or so, although the first step was over 50 secs/step, and then it decreased). This is with a GeForce 1080 Ti. Is the speed normal? What loss should I expect for good performance? And what number of steps? 877K like it is mentioned in the Readme?

Edit: A bit later, it gets a bit faster. However, the loss then from 5k to 10k does not really improve anymore:

    Step 4311    [1.825 sec/step, loss=0.12430, avg_loss=0.12537]
    Step 11344   [1.746 sec/step, loss=0.12565, avg_loss=0.12844]

These information would be nice to have also in the Readme.

**Comment by keithito** [comment]
Added to the README as requested.

**Comment by albertz** [comment]
Thanks!
