### ISSUE TITLE
Question about synthesizing long sentences

### ISSUE THREAD

**Issue by wlxzt** [keithito/tacotron#185]
@keithito 
Hi, here's my question.
I know that if I want to synthesize long sentences, I have to change the "max_iters" parameter to a larger value, but do I need to re-train the model? or I can just use a pre-trained model trained by a small "max_iters" value like "200" and then set the "max_iter" value to "400" or even larger at the time of evaluation.
Looking forward to your reply, thanks.

**Comment by keithito** [comment]
@wlxzt 
It depends. You should be able to increase the length a bit, but if you get too far away from what was trained on, the model may have trouble aligning.
