### ISSUE TITLE
Can't synthesize single letter correctly

### ISSUE THREAD

**Issue by fire-python** [keithito/tacotron#188]
@keithito
Hi, I randomly pick up several letters from 'a' to 'z', trying to synthesize  with your pretrained model, but none can be sythesize correctly. Any idea why? Is it because of the training dataset lack of such sound or the defect of tacotron itself?

**Comment by Starlon87** [comment]
'training dataset lack of such sound'

**Comment by keithito** [comment]
@fire-python, yes, the training data I used doesn't have any single-letter or extremely short phrases like that.
