### ISSUE TITLE
GetConvolveAlgorithms Error.

### ISSUE THREAD

**Issue by dharma-kc** [keithito/tacotron#19]
I am trying to train this model. But after I run the train.py I get the following error:

tensorflow/core/kernels/conv_ops.cc:671] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted (core dumped)

Could you please help me.

**Comment by keithito** [comment]
Can you provide this entire log output? Also, have you checked out this issue:
https://github.com/tensorflow/models/issues/1064
