### ISSUE TITLE
Tacotron 2 slack channel

### ISSUE THREAD

**Issue by codemandosch** [keithito/tacotron#191]
Hi, I have created a slack workspace for discussing tacotron 2, sharing ideas and helping each other out. The most prominent taco2 repos have their own channels. Keithitos taco2-in-progress branch is one of them. A few people have already joined. Come join us!

https://join.slack.com/t/tacotron2/shared_invite/enQtNDA4MzAzMzY4MjcyLTg3N2ZjZDkyZTAyYjdmNDc2MmFmNjA5NTQ0Mzk3NzgyNjljZGE1YWU4OWFmYjFmYzI4OGE2YWM4MGY4NmRkNGY

**Comment by keithito** [comment]
Thanks for the heads up!
