### ISSUE TITLE
How I know if more training is worth it?

### ISSUE THREAD

**Issue by youssefsharief** [keithito/tacotron#211]
I trained for about 46k and the results seems to be good but how could I assess that objectively?

Thank you

Below is the models/stats/loss graph

![image](https://user-images.githubusercontent.com/21158003/45197509-fe21cd00-b261-11e8-8675-f97a000e2be8.png)

**Comment by keithito** [comment]
I don't have a good answer to this question. It's especially hard for speech synthesis because there's not a good way to measure validation loss.
