### ISSUE TITLE
Can't instantiate abstract class TacoTestHelper with abstract methods sample_ids_dtype, sample_ids_shape

### ISSUE THREAD

**Issue by ishandutta2007** [keithito/tacotron#225]
I am getting trying to run Run the demo server

`(env) ishandutta2007@MacBook-Pro:~/Documents/Projects/tacotron2_dacson_ishandutta2007$ python3 demo_server.py --checkpoint pretrained/tacotron-20170720/model.ckpt
`

> Hyperparameters:
>   adam_beta1: 0.9
>   adam_beta2: 0.999
>   batch_size: 32
>   cleaners: english_cleaners
>   decay_learning_rate: True
>   frame_length_ms: 50
>   frame_shift_ms: 12.5
>   griffin_lim_iters: 60
>   initial_learning_rate: 0.002
>   max_iters: 100
>   min_level_db: -100
>   num_freq: 1025
>   num_mels: 80
>   outputs_per_step: 5
>   power: 1.5
>   preemphasis: 0.97
>   ref_level_db: 20
>   sample_rate: 20000
>   use_cmudict: False
> Constructing model: tacotron
> Traceback (most recent call last):
>   File "demo_server.py", line 92, in <module>
>     synthesizer.load(args.checkpoint)
>   File "/Users/ishandutta2007/Documents/Projects/tacotron2_dacson_ishandutta2007/synthesizer.py", line 17, in load
>     self.model.initialize(inputs, input_lengths)
>   File "/Users/ishandutta2007/Documents/Projects/tacotron2_dacson_ishandutta2007/models/tacotron.py", line 73, in initialize
>     helper = TacoTestHelper(batch_size, hp.num_mels, hp.outputs_per_step)
> TypeError: Can't instantiate abstract class TacoTestHelper with abstract methods sample_ids_dtype, sample_ids_shape

**Comment by azraelkuan** [comment]
the class helper have two more abstract methods , you need to implement it.
```
@property
    def sample_ids_shape(self):
        return tf.TensorShape([])
@property
    def sample_ids_dtype(self):
        return tf.int32
```

**Comment by keithito** [comment]
I believe this was fixed in: https://github.com/keithito/tacotron/commit/7b09826434332cb7fdfe58436fbe5c562cd4b9b8
