### ISSUE TITLE
python3 demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt failed

### ISSUE THREAD

**Issue by zhuyiif** [keithito/tacotron#230]
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key model/inference/decoder/Location_Sensitive_Attention/attention_bias not found in checkpoint
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by keithito** [comment]
Please use the tacotron-20180906 checkpoint. The model architecture has changed since the tacotron-20170720 checkpoint was saved.

**Comment by zhangbo2008** [comment]
Good,reply,upfloor
