### ISSUE TITLE
What's meaning of Encoder timestep and decoder timestep?

### ISSUE THREAD

**Issue by peter05010402** [keithito/tacotron#233]
Hello ,all:
In the png, as follow:
what's meaning of size on Encoder timestep and decoder timestep?

![step-110000-align](https://user-images.githubusercontent.com/42974031/48314385-e1a86500-e603-11e8-827a-1ff75943adf3.jpg)

**Comment by begeekmyfriend** [comment]
It equals to the number of frames.

**Comment by peter05010402** [comment]
@begeekmyfriend  thank you for your quick and clear reply!!!
