### ISSUE TITLE
Does altering the batch_size parameter alter the training process in any way? 

### ISSUE THREAD

**Issue by vaibhavthapliyal** [keithito/tacotron#236]
Hi Everyone, 

I am running this code on Hindi dataset which has about 3600 files. Due to hardware constraints I have to reduce the batch_size to 8 to avoid OOM errors. I want to know if this will have effect on attaining alignment or make the training time more.

Thanks
Vaibhav

**Comment by begeekmyfriend** [comment]
Batch size less than 32 will run the risk of failure to learn alignment.
