### ISSUE TITLE
Tacotron plus World vocoder

### ISSUE THREAD

**Issue by begeekmyfriend** [keithito/tacotron#241]
Hey I am glad to inform you that I have succeeded to merge Tacotron model with World vocoder and generated some evaluation results as follows. The results sound not bad but still not perfect. However it shows another way to train different feature parameters with Tacotron. The World vocoder is an open source project and thus everyone can use it for all. Moreover the quality of resynth results from that vocoder is better than that from Griffin-Lim since the three features (lf0[1], mgc[60] and ap[5]) contain not only magnitude spectrograms but also phase information. Furthermore the depth of the features is low enough that we do not need postnet for Tacotron model. The performance of training can be reduced to 0.7 second per step. The inference can also be quick enough even it only works on CPU. So it really worthes trying.

I would like to share my experimental source code with you as follows. Note that it currently only for Chinese mandarin. You may modify it for other languages:
[tacotron-world-vocoder branch](https://github.com/begeekmyfriend/Tacotron-2/tree/mandarin-world-vocoder)
[Python-Wrapper-for-World-Vocoder](https://github.com/begeekmyfriend/Python-Wrapper-for-World-Vocoder)
[pysptk merlin-world-vocoder branch](https://github.com/begeekmyfriend/pysptk/tree/merlin-world-vocoder)
By the way you need use `python setup.py install` and the copy the so file manually into the system path for `pysptk` and python wrapper project.

Besides I also would like to provide two Python scripts for World vocoder resynth test.
[world_vocoder_resynth_scripts.zip](https://github.com/keithito/tacotron/files/2982122/world_vocoder_resynth_scripts.zip)

[world_vocoder_demo.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2714364/world_vocoder_demo.zip)
![image](https://user-images.githubusercontent.com/6031938/50508190-c6ae8900-0abb-11e9-8a1e-fa3566515f1b.png)

**Comment by begeekmyfriend** [comment]
I have modified something on both World vocoder and `pysptk` to make them work on this project. And I have used merlin tool scripts for feature extraction and resynth. It seems the latest version of World vocoder failing to work on this issue. So I open my modified forks here so that everybody can try them.

**Comment by isaiah658** [comment]
> Note that it currently only for Chinese mandarin. You may modify it for other languages

What would need to be changed for it to work with English? I'm interested in trying it but I don't know anything about creating neural networks. I know just enough to use them. If it's too complicated, are you planning to have it work with English later on?

**Comment by begeekmyfriend** [comment]
@isaiah658 You can do it on your own. That is not tough.
First revert the `symbols.py`
https://github.com/begeekmyfriend/Tacotron-2/commit/6abba13160e0a09bba248cb71119b3681e61996c#diff-7163c9c1f4130c23f589899e114afdbd
Second change the cleaner in `hparams.py`
```python
cleaners='english_cleaners',
```
Third choose `LJSpeech` as the option for `train.py`.

**Comment by isaiah658** [comment]
@begeekmyfriend I appreciate the help! Unfortunately I'm having trouble compiling pyworld. I'm clueless when it comes to compiling stuff, but I think I managed to compile pysptk. It made the .so file. Pyworld is proving more difficult though. 

First it wants the "world/synthesis.h" from the world project. So I paste in the world folder with the header files. Then all the other header files refer to "world/macrodefinitions.h" and a couple other files so I remove the "world/" so they refer to the local folder. After that compiling gives several errors starting with `pyworld.cpp:3880:33: error: invalid conversion from CheapTrickOption* to int`. It also says there are `too few arguments on line pyworld.cpp:3880:49`. After that it says D4C_coarse and Synthesize were not declared in scope.

Keep in mind that I am using your modified world vocoder project as you said something in a different comment that it won't work with the latest from mmorise.

I'm probably doing something wrong. Please help me if possible. Thanks!

**Comment by begeekmyfriend** [comment]
```shell
git clone https://begeekmyfriend/pysptk.git
cd pysptk
git submodule update --init
sudo setup.py install
sudo cp build/lib.../...so       /.../python3.6/site-package/pysptk
```

**Comment by isaiah658** [comment]
@begeekmyfriend Thank you very much! I had to make some adjustments in the ljspeech.py file as well. I just looked at the thchs30.py file and copied the needed parts to ljspeech.py. Training is currently working! So after training is done, do I still use the demo_server.py like in the keithito tacotron?

**Comment by begeekmyfriend** [comment]
You might try both `demo_server.py` and `eval.py`. By the way, I have found that the effect on [T2](https://github.com/begeekmyfriend/Tacotron-2/tree/mandarin-world-vocoder) works even better.

**Comment by isaiah658** [comment]
How many steps did it take you to get an alignment with tacotron plus world vocoder?

**Comment by begeekmyfriend** [comment]
Well the composition of T1 + World has some problems in fact for when it goes over 100k steps, the loss begin to rise. I have no idea about such issue. So I just take out the results from that under 100k steps. For T2 + World the loss curves seem normal and the results sound better.
[biaobai_xizang_48000.zip](https://github.com/keithito/tacotron/files/2719790/biaobai_xizang_48000.zip)
![image](https://user-images.githubusercontent.com/6031938/50578570-b0ffe180-0e76-11e9-8f6b-c2f953958ab1.png)

**Comment by isaiah658** [comment]
Unfortunately after 20k training steps the alignment is not improving. It's the same as it was at 1k steps. It's a bunch of green at the top of the graph. I think it's because my dataset is too small and it's actual speech. It's not someone reading lines from a script. When someone reads a script they generally focus more on enunciation than someone who is just talking. The dataset only has 50 minutes of audio.

It would be interesting to try training on an already trained English speaking model. I've been able to get  good results with keithito's tacotron by training on top of the ljspeech model. Training on top of another model also saves me a lot of time because I don't have a GPU to train with.

Just wanted to share my results. I wasn't expecting it to work with my dataset, but I wanted to try it out and see what would happen.

**Comment by begeekmyfriend** [comment]
50 min is too little. 5~10 hour is the least.

**Comment by herenje** [comment]
@begeekmyfriend I ask one more question. In the 'eval_interval' process, the following error occurred.

**TypeError: mgc2sp() got an unexpected keyword argument 'order'**

In your 'datasets/audio.py', please check the function 'sp_denormalize()'.
Checking the pysptk documentation, the 'mgc2sp()' function does not have an order parameter.

**Comment by begeekmyfriend** [comment]
```
git clone https://github.com/begeekmyfriend/Python-Wrapper-for-World-Vocoder.git
cd Python-Wrapper-for-World-Vocoder
git submodule update --init
sudo cp .../*.so  ~/miniconda/.../pyworld
```

**Comment by begeekmyfriend** [comment]
```
git clone https://github.com/begeekmyfriend/pysptk.git
cd pysptk
git submodule update --init
sudo cp build/../pysptk/*.so  ~/miniconda/.../pysptk
```

**Comment by herenje** [comment]
@begeekmyfriend 
Thank you very much for your help. I missed your modification... I think that your modification play a very important role for this work. So I want to study the changes in detail.  Is there some reference to study math or theory related to your modified world-vocoder?

**Comment by herenje** [comment]
@begeekmyfriend 
I am trying to learn using LJspeech data in Tacotron2. The model is now learning up to 25k, bout the voices sound like men and there is no improvement in alignment. I changed only 'cleaners' and 'sample_rate' in 'hprams.py'. I attach the results below. I would appreciate it if you check and any comments.

[step-25000.zip](https://github.com/keithito/tacotron/files/2785225/step-25000.zip)
![step-25000-align](https://user-images.githubusercontent.com/26708789/51575640-40d50080-1ef6-11e9-8742-d455b644f49f.png)
![image](https://user-images.githubusercontent.com/26708789/51575689-62ce8300-1ef6-11e9-887e-5413f6ca91f5.png)

**Comment by begeekmyfriend** [comment]
Alignment might be hard for acoustic features from WORLD vocoder. You might use some extra normalization methods to scale the feature values into some ranges like [-4, 4] and try again. But the actual feature values do not differ a lot. They range [0, 500] and get alignment on some dataset. Anyway you can try it on your own.

**Comment by herenje** [comment]
@begeekmyfriend 
Does your comment mean to normalize the f0 values from wav2world()?

**Comment by begeekmyfriend** [comment]
@herenje You might print the min and max feature values by `np.min` and `np.max` and estimate the proper range.

**Comment by herenje** [comment]
@begeekmyfriend 
What features are you talking about?
f0? sp? ap? or all of them?

This is my latest result. I don't know what causes the interruption(mute?).
[step-35510.zip](https://github.com/keithito/tacotron/files/2786408/step-35510.zip)

**Comment by herenje** [comment]
@begeekmyfriend 
I used the `madarin-world-vocoder` branch of your tacotron2 repository.
I attach min-max sample cases of the three features in using LJSpeech dataset. I don't know how to scale these values. ha-ha T.T
Any comments will help me a lot. : )

![image](https://user-images.githubusercontent.com/26708789/51646142-bb675400-1fba-11e9-837b-593f06e83066.png)

**Comment by begeekmyfriend** [comment]
Oh, I forgot. My branch is only for Chinese mandarin. If you want other language. Please modify some source files like `tacotron/utils/symbols.py` and other related files. Sorry for my carelessness...

**Comment by herenje** [comment]
@begeekmyfriend 
When I checked, `symbols.py` do not have to be modified in English. I only modified `build_from_path()` to work on the LJSpeech metadata format. And I checked that the `text_to_sequence()` in `feeder.py` works fine.

**Comment by begeekmyfriend** [comment]
Try `fft_size` as 1024 and `mcep_alpha` as 0.65. I am not quite sure whether they might help alignment. But you might refer to [merlin scripts](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py#L56-L75).

**Comment by herenje** [comment]
@begeekmyfriend 
I attach my new result after training 250K steps. The change of `fft_size` was effective on voice pitch. But there is still an alignment problem. Currently, it is impossible to generate speech from text. Any comment s is helpful for me. Thank you. 

[step-250000-audio.zip](https://github.com/keithito/tacotron/files/2810304/step-250000-audio.zip)
![step-250000-align](https://user-images.githubusercontent.com/26708789/51949736-1264a180-2471-11e9-959b-3c8137379d25.png)

**Comment by begeekmyfriend** [comment]
You are trying `LJSpeech` corpus right? Unfortunately I have not tried it. It might be not easy to learn alignment for this project. I suggest you can do some normalizations on those feature values like trying scaling those values range [-4, 4].

**Comment by khanuzair680** [comment]
Great work @begeekmyfriend . i was wondering that if we want to try WORLD vocoder for tacotron-2 on LJSpeech. What would be the necessary changes for the current Tacotron-2 + WORLD implementation of yours.
And if we fine tune it for speaker adaptation, how efficient will be the results compared to the weird robotic sound it gives on the LJ Dataset or any other speaker

**Comment by begeekmyfriend** [comment]
@khanuzair680 See https://github.com/keithito/tacotron/issues/241#issuecomment-450536544

**Comment by khanuzair680** [comment]
Thank but I am not able to create or find a ".so" file from the python wrapper or pysptk. I was wondering that whether it was created for python 2.7. I have tried using setup.py an its exiting with an error. I am using following commands:

git clone https://begeekmyfriend/python-wrapper... .git
cd python-wrapper
git submodule update --init
sudo setup.py install(error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
)(isnie build file:  lib.linux-x86_64-2.7  temp.linux-x86_64-2.7
)
sudo cp build/lib.../*.so       /.../python3.6/site-package/pysptk
cp cannot stat: No such file or directory

For pysptk, it is unable to run setup.py. returning with import error on numpy

It would be wonderful if you could guide me in the right direction

**Comment by begeekmyfriend** [comment]
@khanuzair680 
```
python setup.py install
```

**Comment by khanuzair680** [comment]
> @begeekmyfriend I ask one more question. In the 'eval_interval' process, the following error occurred.
> 
> **TypeError: mgc2sp() got an unexpected keyword argument 'order'**
> 
> In your 'datasets/audio.py', please check the function 'sp_denormalize()'.
> Checking the pysptk documentation, the 'mgc2sp()' function does not have an order parameter.

I am facing the similar issue and i am following the instructions for installing python world wrapper and pysptk. Can you guide me a little. I have used all the options deleted and reinstalled pyworld and pysptk

**Comment by begeekmyfriend** [comment]
@khanuzair680 Please check out the right branch mentioned on the 1st floor.

**Comment by khanuzair680** [comment]
@begeekmyfriend Python-wrapper-for-world-vocoder branch is taken from merlin-world while the pysptk is from merlin-world-vocoder. Am i missing something?

**Comment by begeekmyfriend** [comment]
Try `git update --init` for `pysptk`?

**Comment by khanuzair680** [comment]
I am trying the following:
git clone https://github.com/begeekmyfriend/pysptk.git
cd pysptk
git submodule update --init
python setup.py install
sudo cp build/.../pysptk/*.so ../anaconda3/.../site-package/pysptk

**Comment by khanuzair680** [comment]
I have tried uninstall and remove the respective file from python packages an reinstalling them and after that cloning the .so files into them through git process

**Comment by khanuzair680** [comment]
I am installing pyworld through pip separately, and then copying .so into them after cloning your repository. Is this the right way @begeekmyfriend

**Comment by khanuzair680** [comment]
It started working after some tweaks, great work @begeekmyfriend.

**Comment by hyzhan** [comment]
@begeekmyfriend It seems not word well for 16kHz audio? Have you try 16kHz audio?

**Comment by tsungruihon** [comment]
it seems that in your https://github.com/begeekmyfriend/Tacotron-2/tree/mandarin-world-vocoder, the `hparams.py` file does not have `cbhg` related parameters. Does i did something not correct?

**Comment by wpy0521** [comment]
> @begeekmyfriend Thank you very much for your hard work. I have a question about hyper parameters in training. When 'num_bap' is set to 5, an error occurs in the model initialization process because 'bap depth' of the preprocessing result is 1025. The error message is as follows.
> 
> **ValueError: Cannot feed value of shape (32, 1438, 1025) for Tensor 'datafeeder/bap_targets:0', which has shape '(?, ?, 5)'**
> 
> Is it possible to set 'num_bap' to 1025?
> I would appreciate a more detailed explanation of 'bap'. ; )

I've meet the same problem. How did you solve the problem? set 'num_bap' to 1025?

**Comment by tsungruihon** [comment]
@begeekmyfriend  i also found the training time became much more longer. I haven't changed anything but just replace the data.

**Comment by begeekmyfriend** [comment]
Hi everyone, I have upgraded WORLD vocoder into the latest version where we can use havest instead of dio for F0 pitch extraction. The link adress is still on the 1st floor. Any suggestion is welcome! I am now using [T2](https://github.com/begeekmyfriend/Tacotron-2/tree/mandarin-world-vocoder) for mandarin only.

**Comment by begeekmyfriend** [comment]
@hyzhan See https://github.com/mozilla/TTS/issues/9#issuecomment-473743232

**Comment by herenje** [comment]
@begeekmyfriend What is the havest? If I want to apply the latest version, do I need to reinstall `pyworld` ?

**Comment by begeekmyfriend** [comment]
@herenje Of course, please reclone the link on the links on the 1st floor and the resynth scripts are provided as well.

**Comment by begeekmyfriend** [comment]
Focus on T2 currently. Any feedback is welcome https://github.com/begeekmyfriend/Tacotron-2/commit/e40a7b73ac31d299d731439fbabe8921b231a739
![step-13000-align](https://user-images.githubusercontent.com/6031938/55057234-9454fd80-50a3-11e9-933a-1c9781534cd8.png)

**Comment by herenje** [comment]
@begeekmyfriend 
did you succeed in aligning your attention using world vocoder on T2?

**Comment by begeekmyfriend** [comment]
Of course @herenje 
![step-28000-align](https://user-images.githubusercontent.com/6031938/55062423-f10ae500-50b0-11e9-8bcf-1b4bd98f0db1.png)

**Comment by begeekmyfriend** [comment]
I forgot to tell you that for differnt dataset, adjust the `hp.max_frame_num` and `hp.max_text_length` adopted by guided attention as the alignment slope for better convergence.

**Comment by herenje** [comment]
@begeekmyfriend Thank you. One more question. Do I need to install your `pyworld` and `pysptk` repository for using the latest T2 repository?

**Comment by begeekmyfriend** [comment]
@herenje You might install the upstream repo. It works for me.

**Comment by herenje** [comment]
@begeekmyfriend I will try to learn LJSpeech data again in your latest `tacotron2-world-vocoder` repository. Can you tell me what variables I need to care about in `hparams`? Thank you.

**Comment by begeekmyfriend** [comment]
num_mgc = 60
num_lf0 = 1
num_vuv = 1
num_bap = features.shape[1] - num_mgc - num_lf0 - num_vuv

**Comment by herenje** [comment]
@begeekmyfriend I am trying to learn LJSpeech data. It is going well, but attention graph seems to be not well aligned. The parameters I used are followings:
```
	num_mgc = 60
	num_lf0 = 1
	num_vuv = 1
	num_bap = 2
	frame_period = 8
```
![step-38000-align](https://user-images.githubusercontent.com/26708789/55370141-7882a900-5534-11e9-8250-8cf7117b95b9.png)

I know that this may require more learning time. Could I get an answer from the parameters? Any comment please let me know :) I always appreciate your help.

**Comment by begeekmyfriend** [comment]
Please adapt (reduce) your `max_text_length` and `max_frame_num` for the best ratio of N:T.

**Comment by herenje** [comment]
@begeekmyfriend Considering the attention graph, the appropriate ratio is 1:2. Is it right?

**Comment by begeekmyfriend** [comment]
The radio is depends on your dataset.

**Comment by herenje** [comment]
@begeekmyfriend OK. Thank you. I will try it again :)

**Comment by herenje** [comment]
@begeekmyfriend Attention is aligned very quickly. But it still sounds squeaky? shrieking? in learning `LJSpeech dataset`. Can I hear a sample of the results you learned from `mandarin data`?
![step-4500-align](https://user-images.githubusercontent.com/26708789/55379117-bd1f3c00-5556-11e9-9e08-4607a7308f26.png)

**Comment by begeekmyfriend** [comment]
The demo has been shown on the floors where there is spectrogram graph. Maybe I need to reduce the frame period to obtain better quality. However I was told that the fidelity of sample is not as good as that from G&L. The quality is better indeed.

**Comment by begeekmyfriend** [comment]
By the way when you want to hear complete synthesized samples, please wait until the stop token loss reduced to zero.

**Comment by herenje** [comment]
@begeekmyfriend Okay. I have just passed 5,000 steps. I will wait and share the results with you. By the way, when I heard it again, the results of mandarin demo are really good !!! :)

**Comment by begeekmyfriend** [comment]
Typically female corpus performs better than male one both under WORLD and G&L

**Comment by HaoyuanLuo** [comment]
Hi, @begeekmyfriend , long time no see! 

I heard that LieHuXingKong is using the same way as you did to do the mandarin TTS. I have several questions about the T2+WORLD framework. Could you please give me some word?

First, How's your inference speed of the T2+WORLD framework? 

Second, Is there still miss pronunciation or repeat pronunciation exists in the T2+WORLD outputs? 

Third, Did you try to use WaveNet condition on world features? And then combine the Tacotron2 with WaveNet to make vocoder much more natural and fast?

Please forgive me for asking so many questions at once. We are also considering to do the same things as you did, but we need some survey indeed.

**Comment by begeekmyfriend** [comment]
I have no contact with 猎户星空 Maybe there is coincidence.

I have added a rough inference benchmark for WORLD branch https://github.com/begeekmyfriend/Tacotron-2/commit/70c5a62d2e7c6d64991b50bfa3623adde8df7899. Please check it out on your own machine.

In my test mis pronunciation depends much on your dataset and transcript. If you were using Biaobei corpus, I do not think you would run into such problems.

Wavenet is too slow for me but it might works well for developers possessing bundles of GPUs.

Anyway, thank you for question though I do not remember you through those issues...XD

**Comment by oz0s1me** [comment]
Is there any comparison on the performance between GL and WORLD?

**Comment by peter05010402** [comment]
> features

@begeekmyfriend  
What's the meaning of " features.shape[1]"?
Thank you!

**Comment by begeekmyfriend** [comment]
You might print `features.shape` and you will get it.

**Comment by peter05010402** [comment]
Thank you for your reply!

**Comment by oz0s1me** [comment]
> Is there any comparison on the performance between GL and WORLD?

@begeekmyfriend  Have you compared the performance?~

**Comment by peter05010402** [comment]
> You might print `features.shape` and you will get it

@begeekmyfriend 
my training data is 16k; 
Do you think the hparams is ok?
![image](https://user-images.githubusercontent.com/42974031/55792123-887d2880-5af2-11e9-9719-f5b50e4acf22.png)

**Comment by begeekmyfriend** [comment]
@peter05010402 You need to adjust `max_fram_num` and `max_text_length` according to your dataset.

**Comment by peter05010402** [comment]
@begeekmyfriend  Thank you for your quick reply!!!

**Comment by begeekmyfriend** [comment]
Here is biaobei mandarin demo from T2 + WORLD. The f0 feature value prediction is tough for this model.
[xmly_biaobei_world.zip](https://github.com/keithito/tacotron/files/3062975/xmly_biaobei_world.zip)

**Comment by peter05010402** [comment]
> Here is biaobei mandarin demo from T2 + WORLD. The f0 feature value prediction is tough for this model.
> [xmly_biaobei_world.zip](https://github.com/keithito/tacotron/files/3062975/xmly_biaobei_world.zip)

@begeekmyfriend 
It sounds good! 
but How  to reduce squeaky and  shrieking?

**Comment by begeekmyfriend** [comment]
Separate lf0 loss and x10

**Comment by lin88lin8850** [comment]
> biaobai_xizang_48000

Hi, @begeekmyfriend 
I found this demo sounds best, it's better than xmly_biaobei_world.zip from T2 + WORLD. Do you train your model only with BiaoBei dataset or some private dataset?  Any comment please let me know, Thank you very much!

**Comment by begeekmyfriend** [comment]
Give up this solution and turn to [WaveRNN](https://github.com/fatchord/WaveRNN). Feel free to reopen this issue. The accuracy of F0 feature is hard for prediction.
