### ISSUE TITLE
Sharing my results and a thank you...

### ISSUE THREAD

**Issue by isaiah658** [keithito/tacotron#243]
I want to thank keithito and everyone who has contributed to this project. I know nothing about how neural networks truly work other than the basics, but the people responding to questions on here are helpful and friendly to newbies like myself. The documentation is also easy to follow. Thank you for making this and sharing it!

I decided try turning a YouTuber's voice into text-to-speech. The person I chose was EthosLab. His voice has specific characteristics and enunciations. I was curious if those would still show up when using text-to-speech. I was also curious how the end result would sound using a voice that wasn't reading from a script or a book. 

All voice clips were taken from his YouTube videos and manually turned into a dataset. The dataset only has 50 minutes of audio. However, someone mentioned that copying the dataset and making minor changes to speed/pitch can be used as a way to help increase training data for small datasets. So I doubled the size of the dataset by copying all existing audio files and increased the speed by 1%. That meant I had 1.6 hours of audio, but half of it was duplicated with some minor modifications. I also trained on top of the already trained LJ Speech model that keithito provided. I trained for about 30,000 steps. In my opinion the end result turned out good!

This is what the original speaker sounds like. Watch any of his videos to get a feel for his voice: www.youtube.com/user/ethoslab

Here are the results. I tried to mimic Etho's video style and used his text-to-speech voice to narrate everything: https://www.youtube.com/watch?v=OSZ0nq--ihg

In my opinion, copying the dataset and slightly changing the speed on the duplicate data significantly helped make the the voice clearer and not overfit. I trained the model once without the duplicate data and the results weren't nearly as good as the second time I trained with the duplicate data. Might have been a coincidence though.

**Comment by soubhikbarari** [comment]
This is fantastic! And that's a great data augmentation strategy. One question for someone also attempting to create a TTS on a different dataset: did you find that you had to tweak any of the hyperparameters in `hparams.py`, or was this using just the default network configuration? Also, did you try training it from scratch, that is without LJ Speech? Really appreciate you sharing your knowledge!

**Comment by peter05010402** [comment]
HI @isaiah658 ，
what tool do you use to  Speed up the speed of audio while maintain its pitch?
Thanks

**Comment by isaiah658** [comment]
@peter05010402 I used Audacity. Since the files are small, I would import about 200 files at a time, use the Edit Chains and Apply Chains feature to batch apply the speed effect, and export the modified files. Although, a recent Audacity update appears to have made Macros take the place of Edit and Apply Chains. So the process has changed a bit. If you want to change the audio speed without changing the pitch, you can use the Change Tempo effect in Audacity. Personally though I wanted to use the Change Speed effect. The idea behind increasing the dataset is not about changing the speed. It's about changing the dataset slightly in some way that the neural network has two or more of the same sentences, but with small variations. It's sort of equivalent to saying the same sentence multiple times. It might be said a little differently each time. Those variations seem to help the neural network learn what is actually important and not overfit the data. At least that's how it worked for myself and a few other people.
