### ISSUE TITLE
faster synthesis

### ISSUE THREAD

**Issue by mmomin93** [keithito/tacotron#246]
After training the model, the synthesis duration time of speech from text in local host server is very long. How to decrease the synthesis time on a PC system (RAM 8GB) ?

**Comment by keithito** [comment]
Run synthesis on a GPU, if available. Even a slow GPU will beat the CPU. You need to install a version of tensorflow that works with the GPU to do this. See https://www.tensorflow.org/install/gpu

**Comment by MikeyBeez** [comment]
Thank for supplying this info Keith.  It's very good quality, but it's still really slow on a GPU.  It's not usable for real-time TTS. I've been using gTTS, but it's getting to be rather broken these days.  I really want a good local solution for TTS.  espeak and festival stink, however. :(
