### ISSUE TITLE
Demo server won't run - No module named Falcon

### ISSUE THREAD

**Issue by aminbaig** [keithito/tacotron#250]
I have followed the instructions, no errors during install but when I run the command:

python3 demo_server.py --checkpoint /tmp/tacotron-20180906/model.ckpt
I get the following error. 
```
Traceback (most recent call last):
  File "demo_server.py", line 2, in <module>
    import falcon
ModuleNotFoundError: No module named 'falcon'

```
I have also tried the command with eval.py like so:
python3 eval.py --checkpoint /tmp/tacotron-20180906/model.ckpt

But then I get the following error:
```
Traceback (most recent call last):
  File "eval.py", line 4, in <module>
    from hparams import hparams, hparams_debug_string
  File "/home/amin/tacotron/hparams.py", line 1, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

```
Please advise...this does not make sense as everything has installed with no errors.

**Comment by keithito** [comment]
It looks like the dependencies are not installed. Try:
`pip install -r requirements.txt`

If you're using virtualenv or similar, make sure you're in the same environment that you installed the dependencies in.

**Comment by aminbaig** [comment]
Thanks Keith...I was using python3 and pip3...re-ran the commands with them and everything works fine now.
