### ISSUE TITLE
How to contron the tone,volume and speech rate when generate wav file?

### ISSUE THREAD

**Issue by peter05010402** [keithito/tacotron#251]

**Comment by keithito** [comment]
If you want to modify the volume, pitch, or rate of the entire output wav you can do it by applying your favorite audio processing library (for example librosa) here:
https://github.com/keithito/tacotron/blob/a4f5ac3dfc596425206235d931e907b639a60ed4/synthesizer.py#L39

Doing this more generally is a bigger issue. You could try implementing one of these papers:
https://arxiv.org/abs/1803.09047
https://arxiv.org/abs/1803.09017

There may be some implementations already on Github.
