### ISSUE TITLE
error data preproseccing

### ISSUE THREAD

**Issue by lalimili6** [keithito/tacotron#252]
error is:
`~/tacotron$ python3 preprocess.py --dataset ljspeech
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/signal/signaltools.py:1363: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/signal/signaltools.py:1363: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/signal/signaltools.py:1363: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/ubuntu/.local/lib/python3.5/site-packages/scipy/signal/signaltools.py:1363: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
  0%|                                                                                                                | 0/13100 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ubuntu/tacotron/datasets/ljspeech.py", line 60, in _process_utterance
    mel_spectrogram = audio.melspectrogram(wav).astype(np.float32)
  File "/home/ubuntu/tacotron/util/audio.py", line 51, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D))) - hparams.ref_level_db
  File "/home/ubuntu/tacotron/util/audio.py", line 128, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/home/ubuntu/tacotron/util/audio.py", line 133, in _build_mel_basis
    return librosa.filters.mel(hparams.sample_rate, n_fft, n_mels=hparams.num_mels)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,1025) (0,) 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 50, in <module>
    main()
  File "preprocess.py", line 46, in main
    preprocess_ljspeech(args)
  File "preprocess.py", line 21, in preprocess_ljspeech
    metadata = ljspeech.build_from_path(in_dir, out_dir, args.num_workers, tqdm=tqdm)
  File "/home/ubuntu/tacotron/datasets/ljspeech.py", line 33, in build_from_path
    return [future.result() for future in tqdm(futures)]
  File "/home/ubuntu/tacotron/datasets/ljspeech.py", line 33, in <listcomp>
    return [future.result() for future in tqdm(futures)]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)`

**Comment by lalimili6** [comment]
It ran well, it about tensorfllow version

**Comment by ZionLee** [comment]
I also met this problem. So could you please tell me which version should i use?

**Comment by Lukelluke** [comment]
> It ran well, it about tensorfllow version

How did u resolve this problem, i countered with this problem too.:TF ver=1.12

**Comment by Lukelluke** [comment]
> > It ran well, it about tensorfllow version
> 
> How did u resolve this problem, i countered with this problem too.:TF ver=1.12

It owe to the problem of numpy. I change it from 1.16 to 1.15.4 and problem disappear, and the folder of training finally have results come out.
