### ISSUE TITLE
how to train a new model

### ISSUE THREAD

**Issue by buscon** [keithito/tacotron#267]
hi,

it might be a trivial question, but how can I train a new model?

**Comment by wengsiangchan** [comment]
Having same problem here.
I wish to train a new model with self-collected dataset (in English Language).
Can anyone share what is the things we should lookout when training a new model ?

**Comment by keithito** [comment]
There's some information to get started here:
https://github.com/keithito/tacotron/blob/master/TRAINING_DATA.md

Basically collect some speech data (preferably >20 hours), label it, and then train. It's easiest if you use the same format as LJ Speech, but you can also write a preprocessor to handle whatever format you want. For non-English data, see the section in the document linked above.
