### ISSUE TITLE
 Invalid argument: Incompatible shapes

### ISSUE THREAD

**Issue by dp-aixball** [keithito/tacotron#27]
After Step 30 ， an error occurred：
 W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Incompatible shapes: [32,1205,80] vs. [32,1000,80]

help，thanks!

**Comment by keithito** [comment]
Try setting the `max_iters` hyperparameter to a larger value. See here for more context: https://github.com/keithito/tacotron/issues/16

**Comment by dp-aixball** [comment]
some samples too long

**Comment by dp-aixball** [comment]
@keithito thanks
