### ISSUE TITLE
ask for help, load model by tensor-name and sess.run , no response

### ISSUE THREAD

**Issue by Liujingxiu23** [keithito/tacotron#279]
load model as follows, no error, no response, I  can not finger out anything wrong. Ask for help
I try this since I want to change the saved model(check-point) to another format using tf.saved_model.builder.SavedModelBuilder.

with tf.Session(config=config) as sess:
  saver = tf.train.import_meta_graph(meta_path)
  saver.restore(sess, checkpoint_path)
  x = tf.get_default_graph().get_tensor_by_name("datafeeder/inputs:0")
  x_len = tf.get_default_graph().get_tensor_by_name("datafeeder/input_lengths:0")
  y = tf.get_default_graph().get_tensor_by_name("model/inference/dense_1/BiasAdd:0")
  y_out = sess.run(y, feed_dict = {x:inputs, x_len:inputs_length}

**Comment by Liujingxiu23** [comment]
Solved

**Comment by xxoospring** [comment]
i also met this problem, could you tell me the reason?
