### ISSUE TITLE
'NoneType' object has no attribute 'model_checkpoint_path'

### ISSUE THREAD

**Issue by xingyunn** [keithito/tacotron#283]
When running eval.py, the following errors occurred:**'NoneType' object has no attribute 'model_checkpoint_path'**.
I modified the instructions several times and made sure that the checkpoint path entered at the terminal was okay.
This is the logs-tacotron file I have trained 11K times, and the model is still in training. I just copy the data down for testing.
![2019-05-27 10-43-51屏幕截图](https://user-images.githubusercontent.com/51066620/58392579-388bfe00-806d-11e9-8df1-042a25484189.png)
_I've been bothered by this problem for a day and tried many solutions, but none of them worked.I would appreciate it if you could help me solve this problem._

**Comment by xingyunn** [comment]
I have solved this problem. Thank you.

**Comment by markyouyuren** [comment]
I met the same problem. How did you solve it?
