### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by xxoospring** [keithito/tacotron#292]
[Mandarin audio.zip](https://github.com/keithito/tacotron/files/3380638/Mandarin.audio.zip)
Above is my result.（the wave means "Thanks for BiaoBei, Thanks for the author's work , thanks for community" in Mandarin)
Now i want to deploy my model, so i saved model in pb format, but when i restoring pb model, I have encountered many problems. I stuck in these problem for two days.  

here is restore code:  if set mel and linear None, enqueue would throw  error: 
```
Traceback (most recent call last):
  File "TTSPythonWrap2.py", line 81, in <module>
    sess.run(enqueue, feed_dict=feed_dict)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape () for Tensor 'linear_targets:0', which has shape '(?, ?, 1025)'

```
if i set mel and linear an zero ndarray with shape [1,1,80], [1,1,1025],  it seems "is_training" will be set True and throw error :
```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 1 out of bounds.
         [[Node: prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=5, ellipsis_mask=0, end_mask=5, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/Enter, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_1, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_2)]]
         [[Node: prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack/_209 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1776_prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TTSPythonWrap2.py", line 86, in <module>
    wav = sess.run(output)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 1 out of bounds.
         [[Node: prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=5, ellipsis_mask=0, end_mask=5, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/Enter, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_1, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_2)]]
         [[Node: prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack/_209 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1776_prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice', defined at:
  File "TTSPythonWrap2.py", line 44, in <module>
    name='prefix'
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3563, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3563, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3450, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): slice index 0 of dimension 1 out of bounds.
         [[Node: prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=5, ellipsis_mask=0, end_mask=5, new_axis_mask=0, shrink_axis_mask=2, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/Enter, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_1, prefix/model/inference/decoder/while/BasicDecoderStep/TacoTrainingHelper/strided_slice/stack_2)]]
         [[Node: prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack/_209 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1776_prefix/model/inference/encoder_cbhg/bidirectional_rnn/bw/bw/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

restoring code:
```
from load import load_graph, load_graph_map
import tensorflow as tf
import numpy as np
from text import text_to_sequence
from util import audio


sentences = [
    "sil x ia4 v3 t ian1 l iou2 k e4 sp1 t ian1 l iou2 uo3 b u4 l iou2 sil"
]

fix_model_pb = '/home/sxdz/workspace/PycharmProj/tacotron-phone/frozen_model/tacotron-1.pb'
in_out_ops = ['datafeeder/inputs:0', 'datafeeder/input_lengths:0', 'model/stats/linear_outputs:0']


def debug_shape(t):
    print(t.get_shape().as_list())


with tf.Session() as sess:
    # tf.global_variables_initializer().run()
    # tf.local_variables_initializer().run()
    x = tf.placeholder(tf.int32, [None, None])
    x_len = tf.placeholder(tf.int32, [None])
    mel_t = tf.placeholder(tf.float32, [None, None, 80], 'mel_targets'),
    linear_t = tf.placeholder(tf.float32, [None, None, 1025], 'linear_targets')

    input_map = {
        'datafeeder/inputs:0': x,
        'datafeeder/input_lengths:0': x_len,
        'datafeeder/mel_targets:0': mel_t,
        'datafeeder/linear_targets:0': linear_t
    }
    with tf.gfile.FastGFile(fix_model_pb, 'rb') as f:
        graph_def = tf.GraphDef()

    graph_def.ParseFromString(f.read())

    sess.graph.as_default()

    tf.import_graph_def(
        graph_def,
        input_map=input_map,
        name='prefix'
    )


    # x = tf.get_default_graph().get_tensor_by_name('datafeeder/inputs:0')
    # x_len = tf.get_default_graph().get_tensor_by_name('datafeeder/input_lengths:0')
    # mel_t = tf.get_default_graph().get_tensor_by_name('datafeeder/mel_targets:0')
    # linear_tt = tf.get_default_graph().get_tensor_by_name('datafeeder/linear_targets:0')

    queue = tf.get_default_graph().get_operation_by_name('prefix/datafeeder/input_queue')
    enqueue = tf.get_default_graph().get_operation_by_name('prefix/datafeeder/input_queue_enqueue')
    dequeue = tf.get_default_graph().get_operation_by_name('prefix/datafeeder/input_queue_Dequeue')
    output = tf.get_default_graph().get_tensor_by_name('prefix/model/inference/dense/BiasAdd:0')

    cleaner_names = [x.strip() for x in ['transliteration_cleaners']]
    seq = text_to_sequence(sentences[0], cleaner_names)
    # # print(seq)
    x_mel = np.zeros((80,), dtype=np.float32).reshape((1, 1, 80))
    x_linear = np.zeros((1025,), dtype=np.float32).reshape((1, 1, 1025))
    feed_dict = {
        x: [np.asarray(seq, dtype=np.int32)],
        x_len: np.asarray([len(seq)], dtype=np.int32),
        **linear_t: x_linear,
        mel_t: x_mel,**
    }

    sess.run(queue)

    sess.run(enqueue, feed_dict=feed_dict)


    # sess.run(dequeue)
    wav = sess.run(output)




```

**Comment by xiaoyangnihao** [comment]
can you show out the code that how export the model.

**Comment by xxoospring** [comment]
> can you show out the code that how export the model.

```
def save_pb_file(meta_file, ckpt, output_pb_file, output_nodes, deploy=True):
    saver = tf.train.import_meta_graph(meta_file)
    with tf.Session() as sess:
        saver.restore(sess, ckpt)
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,
            input_graph_def=sess.graph_def,
            output_node_names=output_nodes
        )

        if deploy:
            output_graph_def = tf.graph_util.remove_training_nodes(output_graph_def)

        with tf.gfile.GFile(output_pb_file, 'wb') as fw:
            fw.write(output_graph_def.SerializeToString())


meta = '../logs-tacotron/model.ckpt-97500.meta'
in_out_opsPB = ['datafeeder/inputs',
                    'datafeeder/input_lengths',
                    'datafeeder/mel_targets',
                    'datafeeder/linear_targets',

                    'datafeeder/input_queue',
                    'datafeeder/input_queue_enqueue',
                    'datafeeder/input_queue_Dequeue',
                    'model/inference/dense/BiasAdd'
                    ]

save_pb_file(
        meta_file=meta,
        ckpt=meta[:-5],
        output_pb_file='../frozen_model/tacotron-1.pb',
        output_nodes=in_out_opsPB,
        deploy=False
    )
```

**Comment by xiaoyangnihao** [comment]
do you solve this problem now ? I met similar problem.

**Comment by xxoospring** [comment]
> do you solve this problem now ? I met similar problem.

Not yet.

**Comment by sujeendran** [comment]
Hi,
I made a class similar to synthesizer class with just few changes to run on the Deployment ready graph. This should work for you. This model has FIFO QUEUE for training only.
 
```
def load_graph(frozen_graph_filename):
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        # The name var will prefix every node name in graph if needed
        tf.import_graph_def(graph_def, name="")
    return graph

class Inferencer:  
  def load(self, model_path, model_name='tacotron'):
    print('Loading frozen graph for inference: %s' % model_path)
    graph = load_graph(model_path)
    self.input = graph.get_tensor_by_name('inputs:0')
    self.input_lengths = graph.get_tensor_by_name('input_lengths:0')
    self.wav_output = graph.get_tensor_by_name('model/griffinlim/Squeeze:0')
    #OR IF YOU ARE ATTACHING GRIFFINLIM AT INFERENCE TIME USE BELOW
    #self.wav_output = audio.inv_spectrogram_tensorflow(graph.get_tensor_by_name('model/inference/dense/BiasAdd:0')[0])
    self.session = tf.Session(graph = graph)
````

**Comment by xiaoyangnihao** [comment]
thanks，by the way, do you know how to export tacotron model in the saved_model format ？I appreciate any help.

**Comment by xiaoyangnihao** [comment]
@sujeendran thanks，by the way, do you know how to export tacotron model in the saved_model format correctly ？I appreciate any help.

**Comment by sujeendran** [comment]
You can dump the graph def after loading it in synthesizer.py class by adding a extra line at the end of load function: 
`tf.train.write_graph(self.session.graph.as_graph_def(), "models/", "graph.pb", as_text=True)`

Then execute the tensorflow's freeze_graph program to freeze it:
`$python freeze_graph.py --input_graph models/graph.pb --input_checkpoint logs-tacotron/model.ckpt-21000 --output_graph logs-tacotron/freezed.pb --output_node_names model/griffinlim/Squeeze`

**Comment by xiaoyangnihao** [comment]
@sujeendran shouldd saved_model should like this ?
`import os
import numpy as np
import tensorflow as tf
from hparams import hparams
from models import create_model
from util import audio

model_name='tacotron'
model_path = "model"
model_version = 100
base_path = '/home/XXX/werther2/'
checkpoint_path = '/home/XXX/werther2/logs-tacotron/model.ckpt-2000'

with tf.get_default_graph().as_default():
    # 定义你的输入输出以及计算图
    sequence = tf.placeholder(tf.int32, [None, None], 'sequence')
    sequence_len = tf.placeholder(tf.int32, [None], 'sequence_len')
    wave = tf.placeholder(tf.float32, [None], 'wave')

    with tf.variable_scope('model') as scope:
        model = create_model(model_name, hparams)
        model.initialize(sequence, sequence_len)

        wave = audio.inv_spectrogram_tensorflow(model.linear_outputs[0])
    saver = tf.train.Saver()

    # 导入你已经训练好的模型.ckpt文件
    print('Loading checkpoint: %s' % checkpoint_path)
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        saver.restore(sess, checkpoint_path)

        # 定义导出模型的各项参数
        export_path = os.path.join(base_path, model_path, str(model_version))
        print('Exporting trained model to', export_path)
        legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')
        builder = tf.saved_model.builder.SavedModelBuilder(export_path)

        # 定义Input tensor info和Output tensor info
        tensor_info_input = tf.saved_model.utils.build_tensor_info(sequence)
        tensor_info_input_len = tf.saved_model.utils.build_tensor_info(sequence_len)
        tensor_info_output = tf.saved_model.utils.build_tensor_info(wave)

        # 创建预测签名
        prediction_signature = (
            tf.saved_model.signature_def_utils.build_signature_def(
                inputs={'sequence': tensor_info_input,
                        'sequence_len': tensor_info_input_len},
                outputs={'wav_out': tensor_info_output},
                method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

        builder.add_meta_graph_and_variables(
            sess,
            [tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                'predict': prediction_signature},
            legacy_init_op=legacy_init_op)

        # 导出模型
        builder.save(as_text=True)
        print('Done exporting!')`

But I'm not sure right or not, I haven't deploy it successfully yet.

**Comment by xxoospring** [comment]
> Hi,
> I made a class similar to synthesizer class with just few changes to run on the Deployment ready graph. This should work for you. This model has FIFO QUEUE for training only.
> 
> ```
> def load_graph(frozen_graph_filename):
>     with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
>         graph_def = tf.GraphDef()
>         graph_def.ParseFromString(f.read())
>     with tf.Graph().as_default() as graph:
>         # The name var will prefix every node name in graph if needed
>         tf.import_graph_def(graph_def, name="")
>     return graph
> 
> class Inferencer:  
>   def load(self, model_path, model_name='tacotron'):
>     print('Loading frozen graph for inference: %s' % model_path)
>     graph = load_graph(model_path)
>     self.input = graph.get_tensor_by_name('inputs:0')
>     self.input_lengths = graph.get_tensor_by_name('input_lengths:0')
>     self.wav_output = graph.get_tensor_by_name('model/griffinlim/Squeeze:0')
>     #OR IF YOU ARE ATTACHING GRIFFINLIM AT INFERENCE TIME USE BELOW
>     #self.wav_output = audio.inv_spectrogram_tensorflow(graph.get_tensor_by_name('model/inference/dense/BiasAdd:0')[0])
>     self.session = tf.Session(graph = graph)
> ```



> You can dump the graph def after loading it in synthesizer.py class by adding a extra line at the end of load function:
> `tf.train.write_graph(self.session.graph.as_graph_def(), "models/", "graph.pb", as_text=True)`
> 
> Then execute the tensorflow's freeze_graph program to freeze it:
> `$python freeze_graph.py --input_graph models/graph.pb --input_checkpoint logs-tacotron/model.ckpt-21000 --output_graph logs-tacotron/freezed.pb --output_node_names model/griffinlim/Squeeze`

@sujeendran ,thanks a lot for your reply that perfectly solve my problem!

**Comment by japita-se** [comment]
Not work for me:
 def load(self, model_path, model_name='tacotron'):
    print('Constructing model: %s' % model_name)
     
    print('Loading frozen graph for inference: %s' % model_path)
    graph = self.load_graph(model_path)
    self.inputs = graph.get_tensor_by_name('inputs:0')
    self.input_lengths = graph.get_tensor_by_name('input_lengths:0')
    
    self.wav_output = audio.inv_spectrogram_tensorflow(graph.get_tensor_by_name('model/inference/dense/BiasAdd:0')[0])
    self.session = tf.Session(graph = graph)

  def synthesize(self, text):
    cleaner_names = [x.strip() for x in hparams.cleaners.split(',')]
    seq = text_to_sequence(text, cleaner_names)
    feed_dict = {
      self.model.inputs: [np.asarray(seq, dtype=np.int32)],
      self.model.input_lengths: np.asarray([len(seq)], dtype=np.int32)
    }
    wav = self.session.run(self.wav_output, feed_dict=feed_dict)
    wav = audio.inv_preemphasis(wav)
    wav = wav[:audio.find_endpoint(wav)]
    out = io.BytesIO()
    audio.save_wav(wav, out)
    return out.getvalue()

At synthesize time:
AttributeError: 'Synthesizer' object has no attribute 'model'


How to create the model?

**Comment by dimanshu** [comment]
can anyone tell me how to deploy this on TensorFlow serving?
