### ISSUE TITLE
start training from a checkpoint

### ISSUE THREAD

**Issue by ghost** [keithito/tacotron#325]
i want train.py to start from the checkpoint provided in pretrained model. but when i start the training , it doeasnt take the checkpoint of the pretrained model. It starts from the first checkpoint.
p.s. the check point of pre trained model and the new training data are both in logs-tacotron folder

**Comment by Usama0121** [comment]
You need to use the --restore_step argument to start training from checkpoint

Try this command
```
python train.py --restore_step 441000
```
Where 441000 is the checkpoint number 
You might need to rename the checkpoint files as model.ckpt-441000.index and similarly other files

**Comment by saharsyed** [comment]
@Usama0121  Figured that out later. Thankyou.I was looking at one of your responses where you mentioned that the non english data you tried didnt converge even at more than 100 k steps. You  then tried with the kiethos pretrained model and trained your data from that checkpoint. Was your data still non-english? if yes, did it work?

**Comment by Usama0121** [comment]
@saharsyed 
I used Urdu dataset for that as well which required some changes in code and stuff

for training with English dataset make sure that the sampling rate of audios matches the pre-trained models sampling rate which I think was 22k or 16k probably, and the length of audios should be between 7 to 15 seconds these work better, moreover, a female dataset might produce better results

**Comment by saharsyed** [comment]
@Usama0121 . Thankyou for the response. i am trying it for non-english data set . But confused how will it work out with the kiethos  pretrained model that was meant for english. I have my own data of about 3500 utterances.

**Comment by saharsyed** [comment]
@Usama0121 do these steps seem adequate :
step1 : use kietho pretrained models.
step2: use your non english dataset and start training from the checkpoint given for pretrained model in kietho
change cleaner to basic cleaner and change hyperparameters according to your need. ...and may be add your language alphabets in symbols.py

**Comment by Usama0121** [comment]
@saharsyed For using a non-english dataset with the pre-trained model you need to add a transliteration layer that maps your language alphabets to the English alphabets. You can try using the transliteration_cleaners. 
PS having a phonetically rich corpus witch high-quality audios will produce better results

**Comment by ghost** [comment]
ok. Thanks a lot for your feedback

**Comment by hassanShabbir1960** [comment]
@Usama0121  Can you tell me that how much data you used for training? And how were the results ?
