### ISSUE TITLE
How to training by GPU

### ISSUE THREAD

**Issue by thuoctran** [keithito/tacotron#33]
Hi,
I tried to used my GTX1080 for training, but when I run the code, it only used my CPU for training.
What should I do to train the dataset by using my GPU?
Thank you in advance.

**Comment by keithito** [comment]
Do you have the log output? Also, have you been able to train other models using Tensorflow on your GPU? Thanks!

**Comment by thuoctran** [comment]
Sorry my mistake. I want to train with multi GPUs (2 * GTX 1080 TI). How can I enable it? 
Thanks!

**Comment by keithito** [comment]
Sorry, training on multiple GPUs is not supported yet.
