### ISSUE TITLE
Incompatible shapes Issue

### ISSUE THREAD

**Issue by dharma-kc** [keithito/tacotron#34]
I am trying to train tacotron on different language. i.e. Nepali language. I have put my charsets in textinput.py and put them to valid input chars. But whenever I train, it trains upto some steps and throws error like this. 

![screenshot from 2017-08-26 13-43-05](https://user-images.githubusercontent.com/14134622/29739303-9f11d074-8a64-11e7-87af-f2e98af17938.png)

Could you please point me to right direction.

**Comment by zuoxiang95** [comment]
You can see this problem #16

**Comment by keithito** [comment]
The tl;dr is you can set the max_iters hyperparameter to a larger value, for example by adding the flag `--hparams="max_iters=400"`

**Comment by dharma-kc** [comment]
That helps . Thank you. I will close the issue.
