### ISSUE TITLE
training/train.txt'

### ISSUE THREAD

**Issue by AyaLahlou** [keithito/tacotron#342]

**Comment by Lukelluke** [comment]
Could u please tell us how u solve this problem? I countered with this too.

**Comment by AyaLahlou** [comment]
The training folder is created once you preprocess the data. make sure you run the preprocessing command first.

**Comment by Lukelluke** [comment]
> The training folder is created once you preprocess the data. make sure you run the preprocessing command first.

Thank u for ur warmhearted reply . I solved this problem days ago by change the Numpy 1.16.* to 1.15.4 . It's all the fault of that .
Thank u again sincerely .
