### ISSUE TITLE
different outputs_per_step

### ISSUE THREAD

**Issue by aparcho** [keithito/tacotron#35]
Did anyone try to use different outputs_per_step (default is 5)? I have tried to set outputs_per_step to 2 as the paper, but the result is not good as default 5.

**Comment by cozec** [comment]
I checked the code and couldn't find any reference of "outputs_per_step". Not implemented yet?

**Comment by keithito** [comment]
It should work:
https://github.com/keithito/tacotron/search?utf8=✓&q=outputs_per_step

**Comment by cozec** [comment]
is outputs_per_step=2 better then outputs_per_step=5? 
Observed better result in other implementations.

**Comment by keithito** [comment]
I haven't tried, it's possible you'd get a better result.
