### ISSUE TITLE
Training stops around 150k steps

### ISSUE THREAD

**Issue by lgit2017** [keithito/tacotron#37]
I have not had any luck in reaching higher steps. The training stops around 150k steps. Any advice? Has anyone faced something similar?

**Comment by ElevenGameStudios** [comment]
Why (with what message) does it stop? The whole Tacotron setup is known to sometimes produce spikes in the loss graph (exploding loss, which makes the traing stop). if that is what's happening, you can go back a few checkpoints and continue training from there..

**Comment by matanster** [comment]
@ElevenGameStudios Care to refer to where that spiky behavior is documented? is that in the original Tacotron paper or somewhere else?
