### ISSUE TITLE
Dimension mismatch if frame_shift_ms reduced

### ISSUE THREAD

**Issue by ZhukIvan** [keithito/tacotron#44]
Hey ! Thank for you implementation its really great. But I have lots of trouble trying to reduce the frame_shift_ms. In case of 10ms the error comes after 25 steps (with batch_size 16). If I use 5ms error comes immediately. Of course I'v  preprocessed data with that hparams. Can you please explain or may be  help to fix it ?
here is the complete log with error
[tf_error.log](https://github.com/keithito/tacotron/files/1327288/tf_error.log)

**Comment by ZhukIvan** [comment]
Sorry I'm not properly dig into architecture and dimensions. To get properly working tacotron on lower frame_shift_ms you need to expand outputs_per_step to meet increasing steps per file. So to make it work with 5ms hop size you have to set ouputs_per_step = 11 (on ljspeech dataset). If I get it wrong please write the right answer here. Thanks

**Comment by keithito** [comment]
Yes, (frame_shift_ms * outputs_per_step * max_iters) must be at least as long as your longest training example (in milliseconds). With the defaults, this is 12.5 * 5 * 200 = 12500 ms. 

If you decrease frame_shift_ms, you can either increase outputs_per_step or max_iters until the length is sufficient.

**Comment by ZhukIvan** [comment]
Thanks, it's very helpful.
