### ISSUE TITLE
Loss decreases fast but alignment cannot seem to coverage

### ISSUE THREAD

**Issue by npuichigo** [keithito/tacotron#45]
After about 5k step, loss have coveraged to a low level. However, when I visualize the alignment results, it seems that the attention mechanism focus on the same encoder timestep and just not move on.
![image](https://user-images.githubusercontent.com/11533479/30796235-c52e4f60-a203-11e7-8e20-10866e14c226.png)
![image](https://user-images.githubusercontent.com/11533479/30796373-5377c0c6-a204-11e7-8dd2-0bc4c3f99e9c.png)

**Comment by keithito** [comment]
What are the characteristics of your training data? Also, can you attach the train.log file? It will contain the inputs used for generating the samples. Perhaps there may be an issue in how your input text is being converted to symbols?
