### ISSUE TITLE
Waves are all silent when using python2

### ISSUE THREAD

**Issue by npuichigo** [keithito/tacotron#46]
I find that when run this code with python2.7, only silence can be generated. Are there any python3 related features used?

**Comment by keithito** [comment]
I'd highly recommend using python3 if possible. Someone started a PR for python2 (https://github.com/keithito/tacotron/pull/32), but there are still some issues with it.

**Comment by kensun0** [comment]
in py2: 3/5=0; in py3: 3/5=0.6

def _stft_parameters():
  n_fft = (hparams.num_freq - 1) * 2
  hop_length = int(hparams.frame_shift_ms / 1000 * hparams.sample_rate)
  win_length = int(hparams.frame_length_ms / 1000 * hparams.sample_rate)
return n_fft, hop_length, win_length

**Comment by feiyuhong** [comment]
I greatly agree with the opinion of the @kensun0
