### ISSUE TITLE
Gpu problem

### ISSUE THREAD

**Issue by imucsliurui** [keithito/tacotron#51]
I run your code in my GPU server,but my GPU server has four K80 card, I want use two cards only.
How can I achieve it?
 Thank you very much!

**Comment by ICTwangbiao** [comment]
If you just want to use GPU 0 and 1, you can add "export CUDA_VISIBLE_DEVICES=0, 1" into your training shell script.

**Comment by imucsliurui** [comment]
@ICTwangbiao 
yes，Thank you very much！

**Comment by keithito** [comment]
In addition to what @ICTwangbiao said, using a second GPU won't speed things up, so "export CUDA_VISIBLE_DEVICES=0" is fine if you want to use your other GPUs for something.
