### ISSUE TITLE
Incorrect type of hyper parameter

### ISSUE THREAD

**Issue by omgShustrik** [keithito/tacotron#54]
Hello @keithito ! 

I noticed that parameter has  incorrect type. _int_ instead _float_:
https://github.com/keithito/tacotron/blob/9fc433a8702a5e8392254f4c2cc6fe035c64e424/hparams.py#L14
Therefore, when we calculate the window length for [stft](https://github.com/keithito/tacotron/blob/9fc433a8702a5e8392254f4c2cc6fe035c64e424/util/audio.py#L117) we get 0, although we have to get 1000.

**Comment by keithito** [comment]
@omgShustrik Yes, this will not work correctly in Python 2. There are a few other places that are also broken in Python 2. For now, I'd recommend using Python 3.

**Comment by omgShustrik** [comment]
@keithito  It works correctly, sorry.
Perhaps I was wrong in checking.
Thank you!
