### ISSUE TITLE
Sample rate

### ISSUE THREAD

**Issue by metaln37** [keithito/tacotron#56]
Hello, 

I noticed that sample rate in hyperparameters file should be lower for 10% than actual training sets' sample rate. In other case output voice will sound too low. Could you please explain this effect and how can it be fixed?

This question already been asked in issue #39, but no answer there.

**Comment by keithito** [comment]
Can you attach an example? I would have assumed that the sample rate would not make too much of a difference as librosa will resample the training data during the preprocessing step.

**Comment by metaln37** [comment]
I just tryed to reproduce this issue on LJSpeech dataset and everything seems to work normal. So I guess problem was with my dataset (1 word per utterance). Sorry for the false alert.

**Comment by keithito** [comment]
Cool. Thanks for trying it out.
