### ISSUE TITLE
train.py problem

### ISSUE THREAD

**Issue by mathias3** [keithito/tacotron#57]
after preprocessing LJSpeech dataset  and then running: python3 train .py- this stderr happens: 

> Checkpoint path: /home/nbuser/tacotron/logs-tacotron/model.ckpt
Loading training data from: /home/nbuser/tacotron/training/train.txt
Using model: tacotron
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  batch_size: 32
  cleaners: english_cleaners
  decay_learning_rate: True
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 60
  initial_learning_rate: 0.002
  max_iters: 200
  min_level_db: -100
  num_freq: 1025
  num_mels: 80
  outputs_per_step: 5
  power: 1.5
  preemphasis: 0.97
  ref_level_db: 20
  sample_rate: 20000
  use_cmudict: False
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    main()
  File "train.py", line 149, in main
    train(log_dir, args)
  File "train.py", line 58, in train
    feeder = DataFeeder(coord, input_path, hparams)
  File "/home/nbuser/tacotron/datasets/datafeeder.py", line 30, in __init__
    self._metadata = [line.strip().split('|') for line in f]
  File "/home/nbuser/tacotron/datasets/datafeeder.py", line 30, in <listcomp>
    self._metadata = [line.strip().split('|') for line in f]
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4459: ordinal not in range(128)

**Comment by r9y9** [comment]
replacing

https://github.com/keithito/tacotron/blob/9fc433a8702a5e8392254f4c2cc6fe035c64e424/datasets/datafeeder.py#L29

to

```py
with open(metadata_filename, encoding='utf-8') as f:
```

should fix your issue.

**Comment by mathias3** [comment]
Thanks, I was blind!

**Comment by r9y9** [comment]
Ok, I've created a PR #58.
