### ISSUE TITLE
Alignment with vertical stripes question

### ISSUE THREAD

**Issue by chapter544** [keithito/tacotron#60]
Hi all,
I trained tacotron on my private 12 hours dataset. My alignment starts to show up around 30K step. Please see below for an alignment at 54K step. I notice that there are series of stripes on the top, which persist through out the steps. They could get longer or shorter depending on the encoder/decoder size, but they are there. Do we have any explanation to this?
![step-54000-align](https://user-images.githubusercontent.com/18149762/31471987-1f3cb32e-af16-11e7-8472-c439d1d61604.png)

**Comment by tmulc18** [comment]
Does that area always start around 37 encoder steps?  If so, it could be that you don't have many examples where the encoding sequence is greater than 37 so the alignment function never really learns in that input range.

**Comment by chapter544** [comment]
Thanks, that's an interesting observation. However, the area does not always start around the 37th step. See some more alignments below. 

![step-60000-align](https://user-images.githubusercontent.com/18149762/31481267-b8cec802-af4c-11e7-83cb-0eb7f531536e.png)

![step-63000-align](https://user-images.githubusercontent.com/18149762/31481290-d1b95c10-af4c-11e7-9068-60165f4e098c.png)

![step-74000-align](https://user-images.githubusercontent.com/18149762/31481297-d7bfb244-af4c-11e7-906a-10e79bc43866.png)

**Comment by tmulc18** [comment]
Ah yeah so that theory's out the window... How are the results?  Could it be that the model is learning not to attend to anything after the <EOS> token in the input sequence?

**Comment by chapter544** [comment]
Thank you. The results are not so good. The sounds are fine at the beginning and get bad gradually. It could be that the model needs more training or my data is not that big (12 hours). Well, more experiments, i guess.

**Comment by keithito** [comment]
During training, input sequences are padded to the length of the longest sequence in the batch, so I think what you're seeing is attention being allocated to those pad symbols. Since the sum of values in a column is always 1, another way of looking at this is that the model is not very confident in the alignment. It may get better if you try training for longer. You can also try trimming any leading or trailing silences from your training audio. [librosa](https://librosa.github.io/librosa/generated/librosa.effects.trim.html) is useful for this.

**Comment by chapter544** [comment]
@keithito I thought the leading and trailing trim are done with the preprocessing step?

**Comment by keithito** [comment]
No, the preprocessor won't trim unless you add code to do it.

**Comment by chapter544** [comment]
My mistake. I forgot to mention that I did browse through vctk processing source in the other branch and used the _trim_wav function there. Is it it?

**Comment by keithito** [comment]
Yes, that's it. You may want to spot check a few examples to make sure that the parameters to librosa.trim work for your data.
