### ISSUE TITLE
just a question, why 32767 and 0.01, what are they for?

### ISSUE THREAD

**Issue by eezprince** [keithito/tacotron#65]
https://github.com/keithito/tacotron/blob/08989cc3553b3a916a31f565e4f20e34bf19172f/util/audio.py#L15

**Comment by keithito** [comment]
This code is converting the floating-point output of the model to 16-bit values to be saved as a
wav file. 32767 is the maximum value for a 16-bit signed integer (2^15 - 1). The 0.01 prevents
division by zero in case the output is silence.
