### ISSUE TITLE
Question: Deep voice 3 algorithm

### ISSUE THREAD

**Issue by lightsailpro** [keithito/tacotron#70]
Is it possible to add algorithm used in Deep Voice 3 - https://arxiv.org/pdf/1710.07654.pdf? It claims 10 times faster training speed than tacotron and faster inference speed.

**Comment by r9y9** [comment]
Hi, I have been exploring DeepVoice3-like architectures recently. If you are interested, see https://github.com/r9y9/deepvoice3_pytorch for details. Audio samples and pre-trained models are available.

Multi-speaker support is still WIP (https://github.com/r9y9/deepvoice3_pytorch/pull/10, https://github.com/r9y9/deepvoice3_pytorch/issues/1#issuecomment-352254708) but should get ready in a week.
