### ISSUE TITLE
Difference between griffin_lim and griffin_lim_tensorflow

### ISSUE THREAD

**Issue by eezprince** [keithito/tacotron#73]
why angles in _griffin_lim(S) equals **np.exp(1j * np.angle(_stft(y)))**, but in _griffin_lim_tensorflow(S) equals **est / tf.cast(tf.maximum(1e-8, tf.abs(est)), tf.complex64)**? Are they same?

https://github.com/keithito/tacotron/blob/08989cc3553b3a916a31f565e4f20e34bf19172f/util/audio.py#L89

https://github.com/keithito/tacotron/blob/08989cc3553b3a916a31f565e4f20e34bf19172f/util/audio.py#L73

**Comment by keithito** [comment]
Yes, they should both give the same result, but perhaps it would be better to rewrite one of them so they use the same formula.
