### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mcgreenwood** [keithito/tacotron#74]
Hey there, 

I was triying to get the script running but i faced an error.
It always says this following error. 
I´m not a professional coder, so i don´t knwo where to correct it.
Thanks for help!

```
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "train.py", line 152, in main
    train(log_dir, args)
  File "train.py", line 61, in train
    feeder = DataFeeder(coord, input_path, hparams)
  File "/home/parallels/tacotron/datasets/datafeeder.py", line 31, in __init__
    hours = sum((int(x[2]) for x in self._metadata)) * hparams.frame_shift_ms / (3600 * 1000)
  File "/home/parallels/tacotron/datasets/datafeeder.py", line 31, in <genexpr>
    hours = sum((int(x[2]) for x in self._metadata)) * hparams.frame_shift_ms / (3600 * 1000)
IndexError: list index out of range
```

**Comment by keithito** [comment]
Hey @mcgreenwood -- it looks like one of your metadata entries doesn't have enough fields. What dataset are you training on?

**Comment by mcgreenwood** [comment]
Hey @keithito -- I´ve downloaded the LJSpeech-1.0.tar.bz2 dataset. 
I didn´t use any own Datasets for now.

**Comment by keithito** [comment]
Hmm... I'm not really sure what's going on then. What OS and version of Python are you using?

**Comment by mcgreenwood** [comment]
Ahhh .. Sorry, I think it was my fault. I did some adjustments to run it with my own dataset and forgot to change it back.

**Comment by keithito** [comment]
Ah, glad to hear you figured it out.
