### ISSUE TITLE
bad alignment...

### ISSUE THREAD

**Issue by eazhary** [keithito/tacotron#76]
Thanks for a great implementation. I tried with your pre-trained model and it sounds fantastic. 

I tried to train on my own dataset of arabic language, I changed the symbols.py, I used basic_cleaners. I preprocessed the data properly (6235 examples, 28.21 hours). I had to change max_iters to 2300 (cause the utterances are long (as the speaker speaks very slowly -- max is 2 mins 20 secs), I think this might be the problem, it would be hard for the model to find attention in such a long sequence. 

during training the output samples are great, however, alignment is bad... 

Should I continue training $$$...

![step-42000-align](https://user-images.githubusercontent.com/26685844/32991686-f6923312-cd48-11e7-8556-b66bc2484270.png)
[train.log](https://github.com/keithito/tacotron/files/1485627/train.log)

**Comment by MXGray** [comment]
@eazhary
I suggest cutting each WAV file in your dataset to a max of 21 seconds (min can be 1 second and average can be anywhere from 5 to 12 seconds); and
I do this automatically for all WAV files in my dataset directory through pydub's detect silence function. You can read more about Pydub here:
https://github.com/jiaaro/pydub/blob/master/API.markdown
There are other methods to do this, so just see what works for you.
Best of luck!

**Comment by eazhary** [comment]
Can you please share a good alignment image. I need to see what I am aiming for!

**Comment by keithito** [comment]
Here's an example (using the LJ Speech dataset)
![step-35000-align](https://user-images.githubusercontent.com/1945356/33145573-c1b826f4-cf75-11e7-95c7-81f21f6cec15.png)

**Comment by keithito** [comment]
Closing out some inactive issues. Please feel free to re-open.

**Comment by eazhary** [comment]
@Ola-Vish It didnt work because my training data was not good (not due to the model itself). If I had better training data, I would have probably had success.

Meanwhile, you can check my own implementation of a different algorithm on https://github.com/eazhary/dctts2

**Comment by youssefsharief** [comment]
I am currently also researching MSA Arabic TTS. @eazhary and @Ola-Vish would you like to collaborate?

**Comment by firaoll** [comment]
Hi I also tried to train on my own dataset and i got such kind of alignment image and some what different that you attached. Is that good or bad alignment??




![step-114000-align](https://user-images.githubusercontent.com/45657872/57715523-a30d6900-767f-11e9-8bfd-de48b00819b0.png)
