### ISSUE TITLE
tactron is stable on any dataset?

### ISSUE THREAD

**Issue by 493238731** [keithito/tacotron#78]
when I used the about 10k example, total 9 hrs dataset, synthesise used [gTTS](https://github.com/pndurette/gTTS).The attention is aligned after 60k steps, like 
![image](https://user-images.githubusercontent.com/13764760/33308201-65cb19ee-d454-11e7-84e4-c925edcd1797.png)
and when eval stage it sounds as gTTS synthesized.

But I use  another dataset  ( about 50k examples 45 hrs + ) and don't change the hyperparameters, I found that noisy alignment often leads to mispronunciations like 
![image](https://user-images.githubusercontent.com/13764760/33308354-1442cac6-d455-11e7-988e-48661a127e89.png) after 160k steps.

**Comment by keithito** [comment]
It's pretty stable on the LJ Speech dataset. You'll still get some mispronunciations, particularly on things that were outside of the vocabulary in the dataset, but things stay stable as you train longer or when you go from training on a subset of the dataset to the full dataset.

I wouldn't worry too much about the area in the red box above. That's just the model attending to the end token at various places in the input (probably at silences or at other places that could reasonably be the end of a sentence).

**Comment by 493238731** [comment]
Thanks!As you say, I didn't split word with space, and took word without space  as input.As result, it lead to the area in the red box above that seems to noisy alignment.
