### ISSUE TITLE
Problem with "Hello, world."

### ISSUE THREAD

**Issue by geneing** [keithito/tacotron#81]
I tested with the pretrained model (tacotron-20170720) linked to on the github page. I'm hearing interesting things.
"Hello world." sounds normal. However, "Hello, world." turns into "Hell world world". 
Another problem with LJSpeech trained model is that it shortens some vowels: "wrote" turns into "rut". 

Are @MXGray model weights available for download? I'd like to test with the second model too.

**Comment by MXGray** [comment]
@geneing

Here you go:  https://github.com/keithito/tacotron/issues/15#issuecomment-342632496

**Comment by hadiasheri** [comment]
This is my issue too.

**Comment by luweishuang** [comment]
@MXGray  i do python3 eval.py with checkpoint in "https://drive.google.com/file/d/1AtKUeUPp95NCdve2uwXb4JYTVJb1iAt0/view?usp=sharing",  but the generated wavs are all like this 
[audio.zip](https://github.com/keithito/tacotron/files/1633826/audio.zip)
but the sample wavs you generated is very nice, Is the checkpoints wrong or some wrong with hparams?

**Comment by keithito** [comment]
Seems better now with the new model.
