### ISSUE TITLE
Vocoder

### ISSUE THREAD

**Issue by wotulong** [keithito/tacotron#83]
I have trained a model with corpus of Nancy.The synthetic voice is clearly, but it's very different from the voice of a real person.Then I found the synthetic sound is really similar with the sound that synthesis through griffin-lim algorithm with spectrum from the function spectrogram().The audio samples follow:

-audio files:
[audio.zip](https://github.com/keithito/tacotron/files/1553880/audio.zip)
So , is it the problem of the griffin-lim algorithm and should I have to try another vocoder if I want to get a more nature voice?

**Comment by liyz15** [comment]
Have a look at [Deep Voice 2](https://arxiv.org/abs/1705.08947), which used a WaveNet-based vocoder and significantly improved audio quality.

According to #64 , the training could be difficult.

**Comment by wotulong** [comment]
We are working on that now, but still haven't a result.

**Comment by wotulong** [comment]
Wavenet vocoder improve the quality of the audio indeed, but it cost too much time to speech synthesis.

**Comment by mrsylerpowers** [comment]
@wotulong The old wavenet vocorder takes to way to long but Google released a new wavenet. It uses probably density distillation along with other things. This wavenet vocorder is faster that realtime (1000 times faster than the original). It is outlined here and I have yet to see anyone implement it .https://deepmind.com/blog/high-fidelity-speech-synthesis-wavenet/
