### ISSUE TITLE
Training velocity

### ISSUE THREAD

**Issue by bic-user** [keithito/tacotron#88]
Hi,

First of all - thanks for awesome implementation. Apart from working TTS, code itself is great. I plan to inherit quite some TF best practices. 

You released the model which is nice, but I wonder if you could share logdir. I'm interested in training speed (for debug purposes). From deep voice 3 paper it seems to be 4.7sec/step with batch-size 32. That would mean 2 weeks for 250k steps. Is it the case? Does it make sense to look into multiple-GPU training?

Google paper mentions that they use r=2 for evaluation. Does it sound better?

Did you play with model size? Currently most of the layers are 256.What's the effect of putting 64 everywhere? 

Regards

**Comment by keithito** [comment]
The training speed on a GTX 1080 Ti and batch size 32 was around 1.1 sec/step, so you could get up to 250k steps in about 3 days.

I have not had a chance to play around with changing model size or r, but if you or anyone else wants to try it, I'd gladly include or link to your results.
