### ISSUE TITLE
When to terminate the process and what to expect after how many steps?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [keithito/tacotron#9]
I am at 4000 steps now. I let tacotron synthesize "Hallo" and I get this: [Hallo.zip](https://github.com/keithito/tacotron/files/1174997/Hallo.zip). I am wondering how soon I can know that it won't get better and I rather tinker with the hyperparameters - or my input set - than hoping that in a few days of constant rendering it will sound like the samples of the creators.

**Comment by zuoxiang95** [comment]
You should be patient, only 4000 steps is far from enough.

**Comment by ErfolgreichCharismatisch** [comment]
That is no answer to my question.

**Comment by DarkDefender** [comment]
Things like this takes time. As @zuoxiang95 said, 4000 is not enough to know if the parameters are good or not. You have to train it for a very long time to see if it works.

I would say that if it doesn't get any better when you reach 20k step, you can try to tweak things.

**Comment by keithito** [comment]
Until the model learns to attend, you will get poor results.

You can tell when this happens by looking at the alignments (these are dumped as step-xxxxx-align.png. The alignment will go from something like this:
![step-10000-align](https://user-images.githubusercontent.com/1945356/28626626-8441ee80-71ed-11e7-884b-95c76e39c2bf.png)

to something like this:
![step-20000-align](https://user-images.githubusercontent.com/1945356/28626629-8742cf00-71ed-11e7-8857-538bc5037ee7.png)

Once that happens, you can expect to start getting intelligible results. This generally happens by around 20K steps, but will depend a lot on your training data.

**Comment by ErfolgreichCharismatisch** [comment]
> This generally happens by around 20K steps, but will depend a lot on your training data.
Does it matter whether the audio was trimmed at the beginning and end?

**Comment by keithito** [comment]
Yes, it may make a difference. I think the Deep Voice authors reported that they had to trim silence in order to reproduce the Tacotron results (https://arxiv.org/pdf/1705.08947.pdf).

It's pretty straightforward to do so using librosa:
https://librosa.github.io/librosa/generated/librosa.effects.trim.html

**Comment by ErfolgreichCharismatisch** [comment]
They write

> We also find that if the speech in each audio clip does not start at the same timestep, the models are much lesslikely to converge to a meaningful attention curve and recognizable speech; thus, we trim all initial and final silence in each audio clip

yet they do not talk about in between pauses. Do you presume that removing them is beneficial as well?

**Comment by keithito** [comment]
The model will learn to fit the training data, so if the pauses are something you want the model to learn (e.g. the pause after a comma), then you should leave them in. If they're not, then you should remove them.

**Comment by ErfolgreichCharismatisch** [comment]
[This seems to be leading nowhere](https://github.com/keithito/tacotron/files/1179111/align.pictures.zip). The question is, where should I start the change? In [here](https://github.com/keithito/tacotron/issues/8) I shared my setup.

**Comment by keithito** [comment]
Can you attach a few .wavs from your training set as well as the corresponding lines in train.txt? That might help in diagnosing the issue. 

Umlauts and other diacritics end up getting dropped (e.g. "bär" will be converted to "bar"). If that's not what you want, you can transliterate during preprocessing.

**Comment by ErfolgreichCharismatisch** [comment]
I don't want to share my voice files on the public internet. But maybe you can give me/everyone some hints what to look for when 

- creating text files(transliterating during preprocessing) and 
- wave files(frequency, bits, channels, volume, length, overall amount, background noises) as well as 
- hyperparameters(what to change when certain results appear, referring to spectrogram pictures or tensorboard charts) and 
- others properties of value 

in the wiki

**Comment by ErfolgreichCharismatisch** [comment]
Let's start with the audio files. 

1. How many hours proved to be useful at which audio quality? 
1. What did you take care of when assembling the audio files?

**Comment by keithito** [comment]
The results in the README were trained on the [LJ Speech Dataset](https://keithito.com/LJ-Speech-Dataset/). It's about 24 hours of audio, and you can read details on how it was prepared at that site.

There are many open questions, including how much data you need to get a good model, what types of phrases you should record, etc. I encourage you to try answer some of these questions and report back on your results.

**Comment by ErfolgreichCharismatisch** [comment]
Please share 

1. pictures of the first 10 steps (in increments of 500-1000) of a model that turned out reasonable and 
2. pictures of the first 10 steps (in increments of 500-1000) of a model that turned out bad

**Comment by ErfolgreichCharismatisch** [comment]
keithito, will you open the wiki and create stubs about the topics mentioned?

**Comment by keithito** [comment]
Ah, sorry. I thought it was already open, but I was wrong. I've opened it up and added a few stub pages.

**Comment by ErfolgreichCharismatisch** [comment]
I wrote something in the wiki. Please update.

**Comment by keithito** [comment]
Closing out issues that haven't had any activity in a while. Please feel free to reopen if this is still a problem. Thanks.
