### ISSUE TITLE
Using GPU to train and CPU to evaluate

### ISSUE THREAD

**Issue by tuong-olli** [keithito/tacotron#91]
Can TTS train with GPU and evaluate with CPU?
I train model with GTX 1080 Ti and I want to serve model with CPU. When starting the training process, it dump an error:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [276,256] rhs shape= [277,256]
	 [[Node: save/Assign_24 = Assign[T=DT_FLOAT, _class=["loc:@model/inference/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](model/inference/embedding, save/RestoreV2_24)]]
Please to help me!

**Comment by liyz15** [comment]
See #69

**Comment by splitice** [comment]
This would be a huge asset to people looking to generate voice on devices without GPUs.

**Comment by keithito** [comment]
Yes, training on GPU and evaluating on CPU is fine (though it will not be fast enough to be real-time).

The issue here is that you can't change the list of symbols between training and eval. See the issue linked to above for details.

**Comment by splitice** [comment]
Could you please supply some information on how to do that?

**Comment by keithito** [comment]
Tensorflow should use the GPU automatically if available and CPU if not. You can also set CUDA_VISIBLE_DEVICES="" to force CPU usage.

**Comment by splitice** [comment]
Ah there are 2 warnings in relation to CUDA when running in that manner, and it does sit for ~40s on first eval doing ~0% CPU but it does work.

:)

Thanks.
