### ISSUE TITLE
eval.py produces silent .wav files.

### ISSUE THREAD

**Issue by mligema** [keithito/tacotron#92]
Hi ! 
Thanks @keithito for this awesome project! 
Using the pre-trained model tacotron-2017072 I got the demo_server.py working and also eval.py to produce good quality .wav files.
I proceeded to train my own model using Estonian language data (with train.py --hparams='basic_cleaners', custom UTF-8 _characters in symbols.py and a custom preprocessor). While training it produced good quality .wav files (if step % args.checkpoint_interval == 0).
However when trying to synthesize .wav from a specific checkpoint using the eval.py or the demo_server.py it produced 1-2 sec long silent .wav files (no error messages were given). Has anyone come across this issue? I have no idea how to resolve it because no error messages were given.

**Comment by mligema** [comment]
Solved. My training data started with 1+ sec long pause. The silent wav was created by the method find_endpoint which encountered a pause in the beginning of each synthesized wav, cutting the wav to just a short silence.

**Comment by keithito** [comment]
Glad to hear you figured it out!

**Comment by Momoumar** [comment]
@mligema How did you solve this issue?

**Comment by mligema** [comment]
@Momoumar, I think the root of the problem is training data which starts with silence.

You could try cutting the silence from all of your training data with something like [this in stackoverflow remove-silence-at-the-beginning-and-at-the-end-of-wave-files](https://stackoverflow.com/questions/29547218/remove-silence-at-the-beginning-and-at-the-end-of-wave-files-with-pydub)

Or you could do what I did: go to line 37 in tacotron/synthesizer.py 

Option 1: Replace the line 37 `wav = wav[:audio.find_endpoint(wav)] `with `wav = wav[:audio.find_endpoint(wav, min_silence_sec=2.25)]`. That way the method `find_endpoint` (tacotron/util/audio.py)  will require a minimum of 2.25 sec silence, the default was `min_silence_sec=0.8`.

Option 2: Comment out the line 37 -> `#wav = wav[:audio.find_endpoint(wav)] `.

**Comment by mligema** [comment]
@Momoumar try this to cut silence from your training data [https://github.com/mligema/audio](https://github.com/mligema/audio)

**Comment by kavya2425** [comment]
hi,
I am training tacotron in english language with my own database. I am able to generate the wave files properly while training but when  i am eval.py i am getting only silence as the wave.

so i followed option 1 and changed the silence period to wav = wav[:audio.find_endpoint(wav, min_silence_sec=2.25)] only increased the length of the file then followed the option  2 the files size increased to 56 sec but it is also silence.
changed min_silence_sec to 2.25 but did not get the output. so changed it  gradually till 20sec but found increase in the length of file. Most of my training files beginning silence is lessthan 1sec.

**Comment by mligema** [comment]
@kavya2425 then I guess the problem is with the model overfitting/underfitting, not audio.find_endpoint

**Comment by kavya2425** [comment]
Hi i changed few parameters and trained the model. but i am getting the same issue. 
my hparams and terminal output looks like this,
python eval.py --checkpoint tacotron/logs-tacotron/model.ckpt-18000
Hyperparameters:
  adam_beta1: 0.9
  adam_beta2: 0.999
  attention_depth: 256
  batch_size: 16
  cleaners: basic_cleaners
  decay_learning_rate: True
  decoder_depth: 256
  embed_depth: 256
  encoder_depth: 256
  frame_length_ms: 50
  frame_shift_ms: 12.5
  griffin_lim_iters: 60
  initial_learning_rate: 0.002
  max_iters: 900
  min_level_db: -100
  num_freq: 1025
  num_mels: 80
  outputs_per_step: 5
  postnet_depth: 256
  power: 1.5
  preemphasis: 0.97


  prenet_depths: [256, 128]
  ref_level_db: 20
  sample_rate: 20000
  use_cmudict: False
Constructing model: tacotron
Initialized Tacotron model. Dimensions: 
  embedding:               256
  prenet out:              128
  encoder out:             256
  attention out:           256
  concat attn & out:       512
  decoder cell out:        256
  decoder out (5 frames):  400
 decoder out (1 frame):   80
  postnet out:             256
  linear out:              1025
Loading checkpoint: tacotron/logs-tacotron/model.ckpt-18000
Synthesizing: tacotron/logs-tacotron/eval-18000-0.wav
the decoded text_to_seq is : [33, 12, 17, 45, 2, 53, 5, 59, 17, 19, 57, 17, 45, 60, 19, 53, 2, 59, 18, 43, 4, 19, 20, 51, 18, 58, 33, 18, 64, 5, 45, 5, 19, 35, 17, 43, 2, 19, 52, 59, 65, 3, 17, 66, 17, 19, 57, 2, 43, 18, 60, 2, 45, 5, 48, 6, 19, 65, 18, 49, 2, 52, 3, 33, 19, 65, 17, 65, 18, 49, 60, 19, 27, 52, 18, 52, 3, 33, 60, 18, 60, 13, 19, 53, 2, 59, 18, 43, 4, 52, 3, 19, 35, 9, 60, 3, 53, 3, 17, 38, 5, 33, 13, 62, 2, 60, 52, 3, 73, 1]
the input to the decoder is : కొండాపురం మండల పార్టీ అధ్యక్షుడు గంటా నరసింహం మాట్లాడుతూ స్థానిక సంస్థల ఎన్నికల్లో పార్టీని గెలిపించుకోవాలని.
[checkpoint-18000.zip](https://github.com/keithito/tacotron/files/6591308/checkpoint-18000.zip)

please find the output eval.wav. the wave file and alignment generated at step 18000 in attachments
