### ISSUE TITLE
Failed to find checkpoint file!

### ISSUE THREAD

**Issue by StanDex** [keithito/tacotron#94]
I can't run the demo server because of the checkpoint file cannot be found anyway! I'm working on Windows through Anaconda (because there were more problems to launch tacotron through regular Python). Also I could not download and unpack the checkpoint through Curl as the author asks to do

("Download and unpack a model:
`curl http://data.keithito.com/data/speech/tacotron-20170720.tar.bz2 | tar xjC /tmp`")

because this command didn't recognize correctly by Curl; so I had to do this manually: I downloaded the archive by http://data.keithito.com/data/speech/tacotron-20170720.tar.bz2, unpacked it to a folder "tacotron-20170720" and started trying to refer to checkpoint file through the console. I tried every path, different slashes (\ or/), tried to refer to with unpacked archive, tried to move files into a temp, common, C:\ directories etc, tried to type "/localhost/.../", username, so I tried ALL...
But every time when I typing this command (changing the path to the file, certainly):
`python3 demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt` (by the way, the filename "model.ckpt" does NOT exist there; I tried to rename both files and to mention to their original names too)
so, after `Loading checkpoint: /.../` I receive such log:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /.../ : Not found: FindFirstFile failed for: /.../ ; No such process
`

Please help! What am I doing incorrectly? How I should path to the checkpoint model?

Sorry for my English.

**Comment by splitice** [comment]
the checkpoint is not a file, it's the common prefix of the checkpoint files.

I'm not sure about the specific error though, perhaps try using an absolute path.

**Comment by StanDex** [comment]
Thanks for your comment, I tried all possible paths...
Can you describe how you're doing this? You're using absolute path beginning from disk letter? What about slashes - "/" or "\" ?

**Comment by SoulFireMage** [comment]
I have this issue too sadly. Tried all sorts but no joy - I am new to this but having got this far, am disappointed to find there isn't a clear answer?

"Unsuccessful TensorSliceReader constructor: Failed to get matching files on /trained/tacotron-20170720/model.ckpt: Not found: FindFirstFile failed for: /trained/tacotron-20170720 : The system cannot find the path specified."

Where should the files end up please?

**Comment by StanDex** [comment]
@SoulFireMage and the rest of the people:
The actual cause of this problem in missing two files in that single checkpoint archive (_tacotron-20170720.tar_), specifically – `model.ckpt.meta` and single file `checkpoint` (without filename extension) with following content:
```
model_checkpoint_path:` "model.ckpt"
all_model_checkpoint_paths: "model.ckpt"

```
Meta file could be taken from any other checkpoint.
These both files are required, otherwise tacotron don't "see" the checkpoint.
BTW, you can create a bat file for quick run of the synthesizer :)
BTW2, this checkpoint is not perfect as opposed to some excellent results you can find in other issues.

**Comment by FrankLiOnLine** [comment]
I had the same issue. When I type
`python3 demo_server.py --checkpoint /tmp/tacotron-20170720/model.ckpt` 
it always return a tensorflow.python.framework.errors_impl.NotFoundError. Then I tried:
`python3 demo_server.py --checkpoint tmp/tacotron-20170720/model.ckpt`
it works. I just simply removed the first / before tmp.

**Comment by Ayhoenix** [comment]
Can you share the content of the model.ckpt file with me? Thank you very much
